'use strict';

const { Router } = require('express');
const { getPool } = require('../db/pool');
const log = require('../services/logger');

// Homescreen icon image serving — sibling of /visuals/:id (see
// src/routes/visuals.js for the full rationale).
//
// Mounted in server.js BEFORE authMiddleware: the home grid loads these
// with plain <img> tags, and the tiles must render without an extra
// auth dance. The only access control is the unguessable 32-hex id
// (random 16 bytes, generated by app-manifest.reconcileAppIcon) — same
// stance as visuals; an icon discloses only itself.
//
// Icons are immutable per id: the reconcile rotates to a fresh id when
// the committed bytes change and deletes the old row, so the year-long
// immutable cache header is safe (a deleted id just 404s for fresh
// fetchers). No Range support — these are small images, not video.
function appIconRoutes(config) {
  const router = Router();
  const pool = getPool(config);

  router.get('/app-icons/:id', async (req, res) => {
    const id = String(req.params.id || '');
    if (!/^[a-f0-9]{32}$/.test(id)) return res.status(404).end();
    try {
      const { rows } = await pool.query(
        'SELECT content_type, data FROM app_icons WHERE id = $1',
        [id]
      );
      if (!rows.length || !rows[0].data) return res.status(404).end();
      res.set('Content-Type', rows[0].content_type || 'application/octet-stream');
      res.set('Cache-Control', 'public, max-age=31536000, immutable');
      res.send(rows[0].data);
    } catch (err) {
      log.error('app-icons', 'Failed to serve icon', { id, err: err.message });
      res.status(500).end();
    }
  });

  return router;
}

module.exports = { appIconRoutes };
