// Source guards for geolocation permission delegation (#1475).
//
// Permissions Policy is delegated DOWNWARD by the embedding page: a
// cross-origin child frame is excluded from `geolocation` unless the parent's
// <iframe> carries it in `allow`. An app cannot grant itself the capability,
// so without these attributes every embedded app's getCurrentPosition() is
// rejected in a couple of milliseconds with PERMISSION_DENIED and no prompt,
// which is indistinguishable from the user tapping "block".
//
// The shell hosts app content in three frames, and all three must delegate it
// or the same app gains and loses location depending on which surface it was
// opened from:
//   1. #app-iframe        the authed App tab. Two copies of the attribute
//                         contract exist by design (the React component and
//                         the DOM adapter), so both are asserted.
//   2. #app-viewer-frame  the landing page's in-page viewer for public apps.
//   3. #staging-iframe    the staging / dev-session preview.
//
// Plain string assertions on the source, so a refactor cannot silently drop
// the delegation the way its absence was never noticed in the first place.
//
// Run with: node --test tests/iframe-geolocation.test.js
// (public/index.html is generated by the `pretest` step; run via `npm test`.)

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { shellMarkup } = require('./lib/shell-markup');

const read = (rel) => fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');

test('the React app frame delegates geolocation', () => {
  const src = read('frontend/src/features/app-frame/app-frame.tsx');
  assert.match(src, /const ALLOW = 'clipboard-write; pointer-lock; geolocation';/);
});

test('the DOM adapter copy of the app frame delegates geolocation', () => {
  const src = read('public/js/app-view.js');
  assert.match(src, /allow="clipboard-write; pointer-lock; geolocation"/);
});

test('the two app-frame copies agree on the allow value', () => {
  const fromReact = read('frontend/src/features/app-frame/app-frame.tsx')
    .match(/const ALLOW = '([^']+)';/);
  const fromDom = read('public/js/app-view.js')
    .match(/\ballow="([^"]+)"/);
  assert.ok(fromReact, 'React ALLOW constant should be found');
  assert.ok(fromDom, 'DOM adapter allow attribute should be found');
  assert.equal(fromReact[1], fromDom[1]);
});

test('the landing viewer frame delegates geolocation', () => {
  const src = read('frontend/src/features/auth/landing.tsx');
  const block = src.slice(src.indexOf('id="app-viewer-frame"'));
  assert.match(block.slice(0, 200), /allow="geolocation"/);
});

test('the staging preview frame delegates geolocation', () => {
  const src = read('frontend/src/features/staging/staging-overlay.tsx');
  assert.match(src, /allow="pointer-lock; geolocation"/);
});

// The three above are sources; this one is the artifact that actually ships,
// which is what a browser reads.
test('the built shell ships the delegation on its server-rendered frames', () => {
  // #app-viewer-frame is in the landing screen's interior, which mounts on
  // first reveal; the staging frame is in the document. Both are the shell's.
  const html = shellMarkup();
  const staging = html.match(/id="staging-iframe"[^>]*/);
  assert.ok(staging, 'staging-iframe should be present in the built shell');
  assert.match(staging[0], /allow="pointer-lock; geolocation"/);

  const viewer = html.match(/id="app-viewer-frame"[^>]*/);
  assert.ok(viewer, 'app-viewer-frame should be present in the built shell');
  assert.match(viewer[0], /allow="geolocation"/);
});
