// Source guards for microphone permission delegation (#1480).
//
// Same shape as tests/iframe-geolocation.test.js (#1475), and for the same
// reason: Permissions Policy is delegated DOWNWARD by the embedding page, so
// a cross-origin app frame is excluded from `microphone` unless the parent's
// <iframe> carries it in `allow`. An app cannot grant itself the capability.
//
// Without it, getUserMedia({ audio: true }) inside an app frame cannot succeed
// no matter what the user does — and it fails in the most misleading way
// available: no prompt, and a rejection in a couple of milliseconds with
// NotAllowedError / PERMISSION_DENIED, the exact code a real refusal produces.
// An app therefore cannot tell "you were never asked" from "you said no", and
// the naive support answer sends people to a device permission screen they
// were never prompted by. That is what LIVE TRANSLATION hit: speech
// recognition runs entirely in the browser, so the microphone is its primary
// input, and inside the Usernode frame the product degraded to typing.
//
// All THREE surfaces must delegate it or the same app gains and loses the
// microphone depending on which one it was opened from:
//   1. #app-iframe        the authed App tab. Two copies of the attribute
//                         contract exist by design (the React component and
//                         the DOM adapter), so both are asserted.
//   2. #app-viewer-frame  the landing page's in-page viewer for public apps.
//   3. #staging-iframe    the staging / dev-session preview.
//
// Plain string assertions on the source, so a refactor cannot silently drop
// the delegation the way its absence went unnoticed in the first place.
//
// Run with: node --test tests/iframe-microphone.test.js
// (public/index.html is generated by the `pretest` step; run via `npm test`.)

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { shellMarkup } = require('./lib/shell-markup');

const read = (rel) => fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');

test('the React app frame delegates microphone', () => {
  const src = read('frontend/src/features/app-frame/app-frame.tsx');
  assert.match(src, /const ALLOW = '[^']*\bmicrophone\b[^']*';/);
});

test('the DOM adapter copy of the app frame delegates microphone', () => {
  const src = read('public/js/app-view.js');
  const attr = src.match(/\ballow="([^"]+)"/);
  assert.ok(attr, 'DOM adapter allow attribute should be found');
  assert.match(attr[1], /\bmicrophone\b/);
});

test('the landing viewer frame delegates microphone', () => {
  const src = read('frontend/src/features/auth/landing.tsx');
  const block = src.slice(src.indexOf('id="app-viewer-frame"'));
  assert.match(block.slice(0, 200), /allow="[^"]*\bmicrophone\b[^"]*"/);
});

test('the staging preview frame delegates microphone', () => {
  const src = read('frontend/src/features/staging/staging-overlay.tsx');
  assert.match(src, /allow="[^"]*\bmicrophone\b[^"]*"/);
});

// The three above are sources; this one is the artifact that actually ships,
// which is what a browser reads.
test('the built shell ships the microphone delegation on its server-rendered frames', () => {
  const html = shellMarkup();

  const staging = html.match(/id="staging-iframe"[^>]*/);
  assert.ok(staging, 'staging-iframe should be present in the built shell');
  assert.match(staging[0], /allow="[^"]*\bmicrophone\b[^"]*"/);

  const viewer = html.match(/id="app-viewer-frame"[^>]*/);
  assert.ok(viewer, 'app-viewer-frame should be present in the built shell');
  assert.match(viewer[0], /allow="[^"]*\bmicrophone\b[^"]*"/);
});

// Delegation is not a grant, and the docs must not imply it is: the browser
// still prompts per origin and the user can refuse.
test('the app conventions list microphone as delegated, and stop calling it withheld', () => {
  const doc = read('src/prompts/app-conventions.md');
  const section = doc.slice(doc.indexOf('## Browser capabilities in the app frame'));
  const body = section.slice(0, section.indexOf('\n## ', 10));

  assert.match(body, /\| `microphone` \| `navigator\.mediaDevices\.getUserMedia/,
    'microphone is in the delegated table');
  // The old text named microphone in the NOT-delegated list. An app author
  // reading that would never try, which is the failure this fixes.
  const withheld = body.slice(body.indexOf('**Everything else is not delegated**'));
  assert.doesNotMatch(withheld.slice(0, 200), /microphone/,
    'microphone is no longer listed as withheld');
  // Still honest about what delegation does and does not do.
  assert.match(body, /Delegation is not a grant/);
});
