// Source guards for geolocation delegation — now a GATED capability (#2219).
//
// ── What this file used to assert, and why it changed ──────────────────
//
// #1475 added `geolocation` to the `allow` attribute of all three app
// frames, because Permissions Policy is delegated DOWNWARD by the embedding
// page: without it every embedded app's getCurrentPosition() was rejected in
// a couple of milliseconds with PERMISSION_DENIED and no prompt. That was
// right, and the delegation it added was unconditional — every app, every
// frame, no platform gate.
//
// #2219 is the other half. Unconditional delegation has two consequences
// that only show up once you know how browsers attribute a nested frame's
// request:
//
//   1. Under permission delegation the browser attributes a cross-origin
//      child's request to the TOP-LEVEL origin. So the prompt a person saw
//      read "my.onhomeroom.com wants to know your location" and never named
//      the app that had actually asked.
//   2. That answer is remembered PER ORIGIN. Once granted to the platform,
//      every other app inherited it silently, with no second prompt.
//
// So the browser's own prompt cannot tell one app from another, and the
// platform's can. `geolocation` is now one of nine gated capabilities,
// delegated to an app's frame only when the signed-in user has granted it to
// THAT app and the app declared it in its dapp.json.
//
// What this file pins now is the shape of that change on all three frames:
// none of them carries `geolocation` in a static attribute any more, the App
// tab builds its value from the grant set, and the other two are the ungated
// base. The catalogue contract itself is tests/app-permissions.test.js.
//
// Plain string assertions on the source, so a refactor cannot silently put
// the blanket delegation back the way its absence was never noticed in the
// first place.
//
// Run with: node --test tests/iframe-geolocation.test.js
// (public/index.html is generated by the `pretest` step; run via `npm test`.)

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { shellMarkup } = require('./lib/shell-markup');

const read = (rel) => fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');

const BASE_ALLOW = 'clipboard-write; pointer-lock';

test('geolocation is a GATED capability, not part of the ungated base', () => {
  const policy = read('frontend/src/features/app-frame/app-frame-policy.js');
  assert.match(policy, /export const UNGATED_CAPABILITIES = \['clipboard-write', 'pointer-lock'\];/);
  const gated = policy.slice(policy.indexOf('GATED_CAPABILITIES = ['));
  assert.match(gated.slice(0, 400), /'geolocation'/);
});

test('the React app frame delegates from the grant set, not a constant', () => {
  const src = read('frontend/src/features/app-frame/app-frame.tsx');
  // `look` is the frame's own record: the mounted app's, or a kept one's (#2902).
  assert.match(src, /allow=\{look\.allow\}/);
  // The constant this replaced must be gone, not merely unused.
  assert.ok(!src.includes("const ALLOW = "), 'the flat ALLOW constant is retired');
  assert.ok(!/allow="[^"]*geolocation/.test(src), 'no static geolocation delegation');
});

test('setSrc writes the permission policy before the navigation that reads it', () => {
  // The whole mechanism rests on this ordering: a container policy is
  // computed at navigation, so an `allow` written after `src` applies to
  // nothing. Assert the publish precedes the assignment in the source.
  const src = read('frontend/src/features/app-frame/app-frame-bridge.js');
  const publish = src.indexOf('allow: allowAttribute(granted)');
  const assign = src.indexOf('el.src = src;');
  assert.ok(publish > 0, 'setSrc publishes the allow value');
  assert.ok(assign > publish, 'and does so BEFORE assigning src');
});

test('the DOM adapter copy builds allow from the same catalogue', () => {
  const src = read('public/js/app-view.js');
  assert.match(src, /_appIframeUngated: \['clipboard-write', 'pointer-lock'\]/);
  assert.match(src, /el\.setAttribute\('allow', AppView\._allowAttribute\(granted\)\);/);
  assert.ok(!/allow="clipboard-write; pointer-lock; geolocation"/.test(src),
    'the blanket delegation is gone from the adapter');
});

test('the two app-frame copies agree on the ungated base', () => {
  const fromReact = read('frontend/src/features/app-frame/app-frame-policy.js')
    .match(/export const UNGATED_CAPABILITIES = \[([^\]]+)\]/);
  const fromDom = read('public/js/app-view.js')
    .match(/_appIframeUngated: \[([^\]]+)\]/);
  assert.ok(fromReact, 'policy UNGATED_CAPABILITIES should be found');
  assert.ok(fromDom, 'DOM adapter _appIframeUngated should be found');
  assert.equal(fromReact[1].trim(), fromDom[1].trim());
});

test('the landing viewer frame delegates the ungated base only', () => {
  // A signed-out visitor holds no grants, so there is nobody to hold one.
  const src = read('frontend/src/features/auth/landing.tsx');
  const block = src.slice(src.indexOf('id="app-viewer-frame"'));
  assert.match(block.slice(0, 200), new RegExp(`allow="${BASE_ALLOW}"`));
});

test('the staging preview frame delegates the ungated base only', () => {
  // A preview shows a build the group has not voted in yet.
  const src = read('frontend/src/features/staging/staging-overlay.tsx');
  assert.match(src, new RegExp(`allow="${BASE_ALLOW}"`));
});

// The three above are sources; this one is the artifact that actually ships,
// which is what a browser reads.
test('the built shell ships no blanket geolocation on its server-rendered frames', () => {
  // #app-viewer-frame is in the landing screen's interior, which mounts on
  // first reveal; the staging frame is in the document. Both are the shell's.
  const html = shellMarkup();
  const staging = html.match(/id="staging-iframe"[^>]*/);
  assert.ok(staging, 'staging-iframe should be present in the built shell');
  assert.match(staging[0], new RegExp(`allow="${BASE_ALLOW}"`));

  const viewer = html.match(/id="app-viewer-frame"[^>]*/);
  assert.ok(viewer, 'app-viewer-frame should be present in the built shell');
  assert.match(viewer[0], new RegExp(`allow="${BASE_ALLOW}"`));

  // The point of the change: no frame the shell prerenders hands an app
  // location without a grant behind it.
  assert.ok(!/allow="[^"]*geolocation[^"]*"/.test(html),
    'no prerendered frame carries a static geolocation delegation');
});
