// Offline session boot + the visible offline state (#1021).
//
// The reported symptom was that reloading the app on a bad connection
// signed the user out: /api/auth/me threw, boot treated that exactly like
// a 401, and the landing page appeared. Nothing on screen said "offline" —
// the amber strip is in normal flow and the auth screens are opaque
// `fixed inset-0 z-40` overlays painted straight over it — so the only
// available reading was "I've been logged out", and the sign-in form the
// user then reached could not possibly succeed.
//
// The suite has no DOM, so the UI layers are pinned the way the rest of
// the shell tests pin theirs: by asserting on stable source tokens. That
// is deliberately shallow, but it catches the failure that actually
// happened here — a piece of the chain being dropped or renamed so the
// offline state stops being reachable end to end.
//
// Run with: node --test tests/offline-session-boot.test.js

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const PUBLIC = path.join(__dirname, '..', 'public');
const read = (rel) => fs.readFileSync(path.join(PUBLIC, rel), 'utf8');

const APP = read('js/app.js');
// The connectivity engine is React-side since #1078 retired /js/offline.js;
// its behaviour is unchanged and this file still asserts against it.
const OFFLINE = fs.readFileSync(
  path.join(__dirname, '..', 'frontend', 'src', 'lib', 'offline.ts'), 'utf8',
);
const AUTH = read('js/auth-screens.js');
// The anonymous screens are crossing over to React one chunk at a time
// (#1080 chunk C), so their submit guards live in whichever half owns the
// screen. Everything below asserts against the union.
const FRONTEND = (rel) =>
  fs.readFileSync(path.join(__dirname, '..', 'frontend', 'src', rel), 'utf8');
const AUTH_SHARED = FRONTEND('features/auth/shared.ts');
const AUTH_SCREENS_TSX = ['features/auth/landing.tsx', 'features/auth/login.tsx']
  .map(FRONTEND).join('\n');
const AUTH_WAITING_TSX = FRONTEND('features/auth/waiting.tsx');
// Moved into the React bundle with #settings-screen (#1081 chunk D).
const SETTINGS = FRONTEND('features/settings/settings.js');
const { HOME_SRC: HOME } = require('./helpers/home-modules');
const CSS = read('css/app.css');
const HTML = read('index.html');
// Copy assertions below match against DECODED text. public/index.html is
// generated by the React shell build now, and React escapes an apostrophe to
// &#x27; — so `You're offline` is present on screen but absent from the raw
// bytes. Decoding compares what the user actually reads.
const { decodeEntities } = require('./helpers/html-tokens');
const DAPP = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', 'dapp.json'), 'utf8'
));

// Body of a top-level App method, from its name to the next method at the
// same indent. Good enough to keep assertions from matching a token that
// lives somewhere else entirely in a 4000-line file.
function appMethod(name) {
  let start = APP.indexOf(`\n  ${name}(`);
  if (start === -1) start = APP.indexOf(`\n  async ${name}(`);
  assert.ok(start > -1, `App.${name} not found`);
  const rest = APP.slice(start + 3);
  const end = rest.search(/\n  \},\n/);
  return rest.slice(0, end === -1 ? rest.length : end);
}

// ── The durable session snapshot ─────────────────────────────────────

test('the snapshot is versioned, age-bounded and written on sign-in', () => {
  assert.match(APP, /SESSION_SNAPSHOT_KEY:\s*'usernode\.session\.v1'/);
  assert.match(APP, /SESSION_SNAPSHOT_MAX_AGE_MS:/);
  // enterAuthed is the one place a session becomes real, so it is the one
  // place the snapshot is written.
  assert.match(appMethod('enterAuthed'), /saveSessionSnapshot\(App\.user\)/);
});

test('reading a snapshot rejects one that has aged out', () => {
  const body = appMethod('readSessionSnapshot');
  assert.match(body, /SESSION_SNAPSHOT_MAX_AGE_MS/);
  assert.match(body, /clearSessionSnapshot\(\)/);
});

test('every snapshot access tolerates a hostile localStorage', () => {
  // Private mode / quota / disabled storage must degrade to "no offline
  // session", never throw out of boot.
  for (const name of ['saveSessionSnapshot', 'readSessionSnapshot', 'clearSessionSnapshot']) {
    assert.match(appMethod(name), /try\s*\{/, `App.${name} has no try/catch`);
  }
});

test('the snapshot is display-only — it is never treated as a credential', () => {
  // Nothing may read the snapshot to decide what the user is ALLOWED to
  // do; the cookie stays the sole credential and the server stays the
  // sole judge. The only consumers are the boot screen choice and the
  // reconcile that replaces it.
  // TWO reads, which is what the note above already describes: the boot
  // SCREEN choice (`_applyBootScreen`, which picks the root a cold document
  // reveals before the router can) and `init`'s fallback when /api/auth/me
  // never answers. Both are display-only and both are self-correcting. The
  // count is asserted rather than left open because a third reader is how a
  // display-only record turns into a credential by accident.
  const uses = [...APP.matchAll(/App\.readSessionSnapshot\(\)/g)];
  assert.equal(uses.length, 2,
    'the snapshot is read at boot twice: which screen to show, and whether to '
    + 'enter authed when the server said nothing');
  // Located by its ASSIGNMENT, not appMethod: like `App._foregroundResync`
  // above it, this one hangs off App after the literal, because the call that
  // runs it at module scope has to come after the object exists.
  const at = APP.indexOf('App._applyBootScreen = function');
  assert.ok(at > -1, 'App._applyBootScreen not found');
  const bootScreen = APP.slice(at, APP.indexOf('\n};', at));
  assert.match(bootScreen, /!!App\.readSessionSnapshot\(\)/,
    'the boot-screen read is coerced to a BOOLEAN at the call site — it asks '
    + 'whether this device was signed in, never who it was signed in as');
  assert.ok(!/snapshot[^\n]*isAdmin|isAdmin[^\n]*snapshot/i.test(APP),
    'no privilege decision may be derived from the snapshot');
});

// ── Three-outcome boot ───────────────────────────────────────────────

test('boot distinguishes "server said no" from "server said nothing"', () => {
  const init = appMethod('init');
  // Answered-not-ok: authoritative sign-out, drop every cached trace.
  assert.match(init, /_dropCachedSession\(\)/);
  // Never answered: fall back to the snapshot rather than the landing page.
  assert.match(init, /readSessionSnapshot\(\)/);
  assert.match(init, /_sessionFromSnapshot = true/);
  assert.match(init, /enterAuthed\(snap\.user\)/);
});

test('the boot session check has a deadline', () => {
  // Without it, a stalled-but-open socket holds boot forever — the white
  // screen half of the bug — even when a snapshot is sitting right there.
  assert.match(APP, /BOOT_SESSION_TIMEOUT_MS:\s*\d+/);
  const body = appMethod('_fetchSession');
  assert.match(body, /AbortController/);
  assert.match(body, /BOOT_SESSION_TIMEOUT_MS/);
  assert.match(body, /clearTimeout/);
});

test('the stale boot comment claiming a login-screen offline guard is gone', () => {
  // It described behaviour that did not exist and was part of why the gap
  // went unnoticed. The guard exists now (see below) — the comment must
  // not be the only thing asserting it.
  assert.ok(!/login screen refuses submits while offline/.test(APP));
});

test('a snapshot boot skips the calls that can only fail offline', () => {
  const body = appMethod('enterAuthed');
  assert.match(body, /if \(!App\._sessionFromSnapshot\) App\.connectEvents\(\)/);
  assert.match(body, /!App\._sessionFromSnapshot && window\.Kudos/);
  assert.match(body, /!App\._sessionFromSnapshot && window\.AiCredit/);
});

// ── The shell boots on the snapshot and verifies behind it ───────────────
//
// The session read used to be the GATE: nothing painted until /api/auth/me
// answered, which on a 150ms link was ~250ms of the ~1100ms to a usable
// board and the last serial network wait in the boot chain. The snapshot
// existed the whole time and could have answered it — it was wired as the
// fallback for when the read FAILED rather than as the thing the shell
// starts from. This is what a native app does: read the session out of the
// keychain synchronously, render from the local store, discover auth lazily.

test('a device that has booted here before paints before it asks', () => {
  const init = APP.slice(APP.indexOf('async init()'), APP.indexOf('async _fetchSession()'));
  // The snapshot read comes FIRST, and the boot returns on it without ever
  // awaiting the session read.
  const snapAt = init.indexOf('const snap = App.readSessionSnapshot();');
  const readAt = init.indexOf('res = await App._fetchSession();');
  assert.ok(snapAt !== -1 && readAt !== -1);
  assert.ok(snapAt < readAt, 'the snapshot is consulted before the network is');
  assert.match(init.slice(snapAt),
    /if \(snap\) \{\s*App\._sessionFromSnapshot = true;\s*App\.enterAuthed\(snap\.user\);[\s\S]{0,200}?App\._reconcileSession\(\{ fromBoot: true \}\);\s*return;/,
    'and the verification runs BEHIND the painted shell, not in front of it');
  // Not awaited — that is the whole point.
  assert.doesNotMatch(init, /await App\._reconcileSession\(\)/);
});

test('a device with no snapshot still waits for the answer', () => {
  // Nothing to be optimistic WITH: the read is the only answer there is, and
  // the three outcomes (#1021) are unchanged.
  const init = APP.slice(APP.indexOf('async init()'), APP.indexOf('async _fetchSession()'));
  const tail = init.slice(init.indexOf('res = await App._fetchSession();'));
  assert.match(tail, /if \(res && res\.ok\)/);
  assert.match(tail, /App\._dropCachedSession\(\);\s*await App\.enterAnonymous\(\);/,
    'an answered 401 is still authoritative and still drops every cached trace');
  assert.match(tail, /window\.Offline\?\.nudge\(\)[\s\S]{0,200}?await App\.enterAnonymous\(\);/,
    'no answer and no snapshot is the offline anonymous boot');
});

test('the unverified-session guards are what make an optimistic boot safe', () => {
  // _sessionFromSnapshot is now true on EVERY boot for a returning device,
  // not just an offline one, so everything these guards hold back is held
  // back far more often. Each one is a session-gated call that would be a
  // guaranteed 401 against a session that has ended.
  // Bounded by the sv:authed dispatch, which is unique and sits after every
  // guard below. `App.restoreFromHash();` is NOT a bound — enterAuthed's
  // waiting-room branch calls it early, and slicing there cut the guards off.
  const authed = APP.slice(APP.indexOf('enterAuthed(user) {'),
    APP.indexOf("new CustomEvent('sv:authed'"));
  for (const held of [
    /if \(!App\._sessionFromSnapshot\) App\.saveSessionSnapshot\(App\.user\);/,
    /if \(!App\._sessionFromSnapshot\) App\.connectEvents\(\);/,
    /if \(!App\._sessionFromSnapshot && window\.Kudos\?\.Budget\?\.init\)/,
    /if \(!App\._sessionFromSnapshot && window\.AiCredit\?\.Budget\?\.init\)/,
    /if \(!App\._sessionFromSnapshot && window\.SessionState\)/,
  ]) assert.match(authed, held);
  // And the boot session read is published only on the VERIFIED path — a
  // last-known user is not an answer to "who is signed in".
  assert.match(authed, /if \(!App\._sessionFromSnapshot\) App\._publishBootSession\(\{ user \}\);/);
});

test('every held-back call is started again when the session is verified', () => {
  const rec = APP.slice(APP.indexOf('async _reconcileSession({'),
    APP.indexOf('// ── Staged boot'));
  assert.match(rec, /App\.connectEvents\(\);/);
  assert.match(rec, /Kudos\.Budget\.init\(\)/);
  assert.match(rec, /AiCredit\.Budget\.init\(\)/);
  // These two were held by the same guard and had no restart at all. Missing
  // them was invisible while this path was offline-only and would have been
  // a session with no state on every load once it became the ordinary one.
  assert.match(rec, /SessionState\.start\(\)/,
    'session state has to start somewhere once the session is real');
  assert.match(rec, /TermsFirstRun\?\.maybePrompt\?\.\(\)/,
    'terms-first-run bails on an unverified session, and its sv:authed '
    + 'listener is { once: true } — so it never gets a second chance by itself');
  // The disconnect-recovery sweep belongs to the RECONNECT path. On a boot
  // promotion the screen was painted moments ago from this same session's
  // data, so re-running half a dozen loads over it is waste — and it landed
  // on top of the ?shot= dialog two proposal checks photograph.
  assert.match(rec, /if \(!fromBoot\) \{\s*try \{ App\.resyncCurrentView\(\); \}/);
  assert.match(rec, /App\._publishBootSession\(\{ user \}\)/,
    'and this is where the verified answer reaches everyone who joined');
});

test('reconciling handles all four answers, and only one of them is a reload loop risk', () => {
  const rec = APP.slice(APP.indexOf('async _reconcileSession({'),
    APP.indexOf('// ── Staged boot'));
  // 401/403 — the session really did end. The snapshot MUST be dropped
  // before the reload, or the next boot paints the same dead shell and
  // reloads again, forever.
  assert.match(rec, /if \(!res\.ok\) \{\s*App\._dropCachedSession\(\);[\s\S]{0,200}?location\.reload\(\);/);
  const dropAt = rec.indexOf('App._dropCachedSession();');
  const reloadAt = rec.indexOf('location.reload();');
  assert.ok(dropAt !== -1 && dropAt < reloadAt, 'drop the trace BEFORE reloading');
  // Another user — a shell painted for somebody else cannot be repaired.
  assert.match(rec, /String\(user\.id\) !== String\(App\.user\?\.id\)[\s\S]{0,200}?clearSessionSnapshot\(\);\s*location\.reload\(\);/);
  // Platform access decides WHICH SHELL is on screen (enterAuthed sends a
  // viewer without it to the waiting room), so a snapshot that disagrees
  // painted the wrong one. Saving the fresh record first is what stops THIS
  // one looping: the next boot has the right answer.
  assert.match(rec,
    /!!user\.hasPlatformAccess !== !!App\.user\?\.hasPlatformAccess\) \{\s*App\.saveSessionSnapshot\(user\);\s*location\.reload\(\);/);
  // No answer — offline. Stay on the snapshot; this is where the strip
  // belongs, because the shell is up and readable and the thing the viewer
  // needs to know is that it is not live.
  assert.match(rec, /if \(!res\) \{[\s\S]{0,300}?Offline\?\.nudge\(\)/);
  assert.match(rec, /if \(!res\) \{[\s\S]{0,400}?_publishBootSession\(\{ unknown: true \}\)/,
    'and a joiner is told we could not tell, so it reads for itself');
  // Same deadline'd read as the boot: on the boot path this IS the boot's
  // read, and an open-but-stalled socket must not hold it open forever.
  assert.match(rec, /res = await App\._fetchSession\(\);/);
});

test('the snapshot is the whole user record, which is why the shell it paints is right', () => {
  // saveSessionSnapshot stores `user` entire, not an id — so an optimistic
  // boot renders with the correct admin affordances, quota and platform
  // access rather than a stub that would flicker when the read lands.
  assert.match(APP, /localStorage\.setItem\(App\.SESSION_SNAPSHOT_KEY, JSON\.stringify\(\{\s*user, savedAt: Date\.now\(\),/);
  // It is still display-only and still grants nothing: the cookie remains
  // the sole credential, which is the property the whole optimistic boot
  // rests on.
  assert.match(APP, /DISPLAY-ONLY and grants nothing/);
});

// ── The boot session read is published, not repeated ─────────────────────
//
// GET /api/auth/me was fetched TWICE on every document, 16ms apart, and the
// boot queued behind the copy it did not make. Settings.init() mounts from a
// React layout effect at document load on EVERY screen — the byok dot rides
// the Profile screen and DevChat's budget indicator, so its state really is
// needed before #settings is opened — and it read the same endpoint for the
// same fields already on the `user` object App.init was about to fetch.
// Measured on a 150ms link: one read ~250ms, the pair ~420ms.

const vm = require('node:vm');

// settings.js is a classic script with no imports that publishes
// window.Settings, so the REAL shipped source runs here rather than a copy.
function loadSettings({ boot, fetchImpl }) {
  const noop = () => {};
  const sandbox = {
    console, setTimeout, clearTimeout, setInterval, clearInterval,
    Promise, JSON, URL, URLSearchParams, Date, Math, Object, Array,
    String, Number, Boolean, RegExp, Error,
  };
  sandbox.window = sandbox;
  sandbox.globalThis = sandbox;
  sandbox.location = { search: '', hash: '', origin: 'http://x', href: 'http://x/' };
  sandbox.localStorage = { getItem: () => null, setItem: noop, removeItem: noop };
  sandbox.document = {
    getElementById: () => null, querySelector: () => null, querySelectorAll: () => [],
    addEventListener: noop, removeEventListener: noop, readyState: 'complete',
  };
  sandbox.navigator = { userAgent: 'node', onLine: true };
  sandbox.calls = [];
  sandbox.fetch = (url) => {
    sandbox.calls.push(String(url));
    return Promise.resolve(fetchImpl ? fetchImpl(String(url)) : { ok: false });
  };
  if (boot !== undefined) sandbox.App = { bootSession: () => Promise.resolve(boot) };
  vm.createContext(sandbox);
  vm.runInContext(SETTINGS, sandbox, { filename: 'settings.js' });
  return sandbox;
}

// Objects built inside the vm carry that realm's Object.prototype, so
// deepStrictEqual (what node:assert/strict gives you) rejects them on
// identity rather than on content. Compare the values, not the realm.
const plain = (v) => JSON.parse(JSON.stringify(v));

test('a verified boot session is joined, not re-fetched', async () => {
  const s = loadSettings({ boot: { user: { hasApiKey: true, keyLast4: '9xyz' } } });
  const j = await s.Settings._readMe('');
  assert.deepEqual(plain(j), { user: { hasApiKey: true, keyLast4: '9xyz' } });
  assert.deepEqual(s.calls, [], 'joining the boot read means asking nobody');
});

test('a boot that answered 401 ends it — asking again gets the same 401', async () => {
  const s = loadSettings({ boot: { signedOut: true } });
  assert.equal(await s.Settings._readMe(''), null);
  assert.deepEqual(s.calls, [], 'a definitive no is an answer, not a reason to retry');
});

test('a boot that never landed falls back to its own read', async () => {
  // `unknown` is the snapshot boot: the stored record is { id, username } and
  // reading it for hasApiKey / walletLinkEnabled would silently answer false
  // for every one. Offline the worker serves this from cache — /api/auth/me is
  // in IMMUNE_API_PATHS — which is exactly what happened before this existed.
  const s = loadSettings({
    boot: { unknown: true },
    fetchImpl: () => ({ ok: true, json: () => Promise.resolve({ user: { hasApiKey: true } }) }),
  });
  const j = await s.Settings._readMe('');
  assert.deepEqual(plain(j), { user: { hasApiKey: true } });
  assert.deepEqual(s.calls, ['/api/auth/me']);
});

test('?demo=1 always reads for itself — it is a different answer, not a stale one', async () => {
  // Staging answers the demo request with a FIXTURE key (`demoKey`), so the
  // boot's plain answer is the wrong answer here, not an older copy of the
  // right one.
  const s = loadSettings({
    boot: { user: { hasApiKey: false } },
    fetchImpl: () => ({ ok: true, json: () => Promise.resolve({ user: { demoKey: true } }) }),
  });
  const j = await s.Settings._readMe('?demo=1');
  assert.deepEqual(plain(j), { user: { demoKey: true } });
  assert.deepEqual(s.calls, ['/api/auth/me?demo=1']);
});

test('a shell with no App at all still reads, rather than hanging', async () => {
  const s = loadSettings({
    boot: undefined,
    fetchImpl: () => ({ ok: true, json: () => Promise.resolve({ user: {} }) }),
  });
  assert.deepEqual(plain(await s.Settings._readMe('')), { user: {} });
  assert.deepEqual(s.calls, ['/api/auth/me']);
});

test('every boot path settles the published read', () => {
  // Settled from enterAuthed / enterAnonymous rather than from init(),
  // because every boot path ends in one of those two — INCLUDING the ?shot=
  // early returns, which never reach the session read at all and would
  // otherwise leave a joiner waiting forever.
  assert.match(APP, /bootSession\(\) \{[\s\S]*?App\._bootSession = new Promise/,
    'the promise is created lazily, so a joiner may arrive before init()');
  const anon = APP.slice(APP.indexOf('async enterAnonymous()'));
  assert.match(anon.slice(0, 600), /App\._publishBootSession\(\{ signedOut: true \}\)/);
  const authed = APP.slice(APP.indexOf('enterAuthed(user) {'));
  assert.match(authed.slice(0, 900),
    /if \(!App\._sessionFromSnapshot\) App\._publishBootSession\(\{ user \}\);/,
    'a snapshot boot publishes nothing here — the shell has a LAST-KNOWN '
    + 'user, not a confirmed one, and _reconcileSession publishes the answer');
  // Settled once. A reload-free login calls enterAuthed again later and a
  // joiner that already resolved is not listening — which is exactly the
  // pre-existing behaviour, not a regression this introduced.
  assert.match(APP, /App\._settleBootSession = null;\s*settle\(outcome\);/);
});

test('Settings no longer opens the boot read a second time', () => {
  // The whole point: exactly one place in settings.js may reach for
  // /api/auth/me at boot, and it is the fallback inside _readMe.
  const body = SETTINGS.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '');
  const reads = body.match(/fetch\(`?\/api\/auth\/me/g) || [];
  assert.equal(reads.length, 1,
    `settings.js reaches for /api/auth/me ${reads.length} times; only _readMe's fallback may`);
  assert.match(body, /const j = await this\._readMe\(meDemoQ\);/,
    'refresh() goes through the join rather than fetching directly');
});

test('reconnecting reconciles the snapshot against the real session', () => {
  const body = appMethod('_reconcileSession');
  // 401 → the session really ended.
  assert.match(body, /_dropCachedSession\(\)/);
  // A different user → the shell was painted for someone else.
  assert.match(body, /String\(user\.id\) !== String\(App\.user\?\.id\)/);
  assert.match(body, /location\.reload\(\)/);
  // Same user → promote to a live session.
  assert.match(body, /_sessionFromSnapshot = false/);
  assert.match(body, /App\.connectEvents\(\)/);
  assert.match(body, /resyncCurrentView\(\)/);
  // ...and it is actually wired to the connectivity event.
  assert.match(APP, /usernode:offline-change[\s\S]{0,200}_reconcileSession/);
});

test('every way out of a session clears the snapshot', () => {
  // Leaving it behind would let the next offline boot paint a signed-in
  // shell for an account that logged out — a worse bug than the original.
  assert.match(SETTINGS, /clearSessionSnapshot/);
  assert.match(AUTH, /clearSessionSnapshot/);
  // Including the waiting-room logout, which does not go through settings.
  // That screen is React now (#1080 chunk C), so its own fallback path is
  // where the call has to be.
  const waitingLogout = AUTH_WAITING_TSX.slice(AUTH_WAITING_TSX.indexOf('const onLogout'));
  assert.match(waitingLogout.slice(0, 800), /clearSessionSnapshot/);
});

// ── The visible offline state ────────────────────────────────────────

test('offline state is published as a body class', () => {
  assert.match(OFFLINE, /classList\.toggle\('is-offline', offline\)/);
});

test('the offline strip outranks the auth overlays and the drawer', () => {
  const rule = CSS.slice(CSS.indexOf('body.is-offline #offline-banner'));
  assert.match(rule.slice(0, 400), /position:\s*fixed/);
  const z = /z-index:\s*(\d+)/.exec(rule.slice(0, 400));
  assert.ok(z, 'the strip has no z-index');
  // Auth overlays are z-40, the drawer panel z-50. Anything at or below
  // those and the strip is invisible exactly when it matters most.
  assert.ok(Number(z[1]) > 50, `z-index ${z[1]} is not above the drawer`);
  // Its space is reserved, so it floats over nothing it would hide.
  assert.match(CSS, /body\.is-offline\s*\{[^}]*padding-top/);
});

test('.offline-only blocks are inert until offline', () => {
  const base = CSS.slice(CSS.indexOf('\n.offline-only {'));
  assert.match(base.slice(0, 120), /display:\s*none/);
  assert.match(CSS, /body\.is-offline \.offline-only \{[^}]*display:\s*block/);
});

test('offline-disabled controls are both greyed and click-proof', () => {
  const rule = CSS.slice(CSS.indexOf('body.is-offline [data-offline-disabled]'));
  assert.match(rule.slice(0, 300), /opacity/);
  assert.match(rule.slice(0, 300), /pointer-events:\s*none/);
});

test('the login screen explains the offline state and gates its controls', () => {
  const screen = HTML.slice(
    HTML.indexOf('id="auth-login-screen"'),
    HTML.indexOf('id="auth-register-screen"')
  );
  const copy = decodeEntities(screen);
  assert.match(screen, /class="offline-only/);
  assert.match(copy, /You're offline/);
  assert.match(screen, /data-offline-retry/);
  // Every control that performs a credential exchange.
  for (const id of ['btn-wallet-sign-in', 'btn-otp-request', 'btn-otp-verify',
    'btn-otp-set-password', 'btn-otp-resend']) {
    const tag = screen.slice(screen.indexOf(`id="${id}"`));
    assert.match(tag.slice(0, 160), /data-offline-disabled/, `${id} is not gated`);
  }
  // ...and the password form's own submit.
  assert.match(screen, /<button type="submit" data-offline-disabled/);
});

test('the landing screen explains the offline state too', () => {
  const screen = HTML.slice(
    HTML.indexOf('id="auth-landing-screen"'),
    HTML.indexOf('id="auth-login-screen"')
  );
  const copy = decodeEntities(screen);
  assert.match(screen, /class="offline-only/);
  assert.match(copy, /You're offline/);
  // Joining the waitlist is a POST; it cannot work offline either.
  const cta = screen.slice(screen.indexOf('id="landing-waitlist-cta"'));
  assert.match(cta.slice(0, 200), /data-offline-disabled/);
});

test('"Try again" is wired once, globally, and re-probes', () => {
  assert.match(OFFLINE, /\[data-offline-retry\]/);
  // lastIndexOf, not indexOf — the module header explains the delegation
  // before the code does it.
  const handler = OFFLINE.slice(OFFLINE.lastIndexOf("closest('[data-offline-retry]')"));
  assert.match(handler.slice(0, 300), /void probe\(\)/);
  // Delegated from the document, so a screen that was hidden when its own
  // module ran still gets a working button.
  assert.match(OFFLINE, /document\.addEventListener\('click'/);
});

test('every credential exchange refuses to submit while offline', () => {
  // Both halves define the same guard — legacy for the screens it still
  // owns, shared.ts for the converted ones.
  for (const [label, src] of [['auth-screens.js', AUTH], ['shared.ts', AUTH_SHARED]]) {
    assert.match(src, /function blockedOffline\(/, `${label} has no guard`);
    // The guard consults the /health probe, not navigator.onLine, which
    // false-positives behind exactly the captive portals that break logins.
    const guard = src.slice(src.indexOf('function blockedOffline('));
    assert.match(guard.slice(0, 900), /Offline\?\?\.isOffline\(\)|Offline\.isOffline\(\)|isOffline\(\)/,
      `${label}'s guard does not consult the probe`);
    assert.ok(!/navigator\.onLine/.test(guard.slice(0, 900)),
      `${label}'s guard reads navigator.onLine`);
  }
  // One guard per submit path: password, otp request/verify/set-password,
  // wallet, register — counted across both halves.
  const uses = [
    ...AUTH.matchAll(/if \(blockedOffline\(/g),
    ...AUTH_SCREENS_TSX.matchAll(/if \(blockedOffline\(/g),
  ];
  assert.ok(uses.length >= 6, `only ${uses.length} submit paths are guarded`);
});

test('home says "offline", not "failed", when the feed cannot load', () => {
  const cat = HOME.slice(HOME.indexOf('Failed to load apps') - 1500);
  assert.match(cat, /Offline\.isOffline\(\)/);
  assert.match(cat, /You're offline/);
  // The generic red failure copy is still there for real failures.
  assert.match(HOME, /Failed to load apps/);
});

// ── Screenshot deep links ────────────────────────────────────────────

test('the offline shots pin connectivity instead of reading it', () => {
  // Capture runners and reviewers always have a working network, so
  // without this the offline UI is unphotographable and the before/after
  // comparison can never be produced.
  const body = appMethod('_applyOfflineShot');
  assert.match(body, /'offline'/);
  assert.match(body, /'offline-signin'/);
  assert.match(body, /Offline\?\.forceOffline\(\)/);
  assert.match(APP, /_applyOfflineShot\(\) === 'offline-signin'/);
  // forceOffline pins the state so a later probe cannot flip it back.
  assert.match(OFFLINE, /export function forceOffline\(\)/);
  assert.match(OFFLINE, /if \(forced\) return/);
  // ...including a probe that was ALREADY in flight when the pin went in.
  // probe() only checks `forced` on entry, so without this guard a nudge()
  // fired a few milliseconds earlier — the global-events socket opening does
  // exactly that — resolves afterwards and silently un-pins the capture
  // (#1054, where ?shot=feedback-queued photographed an online shell).
  assert.match(OFFLINE, /if \(forced && !next\) return;/);
});

test('both offline shots are registered as dapp.json checks', () => {
  const paths = DAPP.tests.map((t) => t.path);
  assert.ok(paths.some((p) => p.includes('shot=offline&') || /shot=offline(#|$)/.test(p)),
    'no ?shot=offline check');
  assert.ok(paths.some((p) => p.includes('shot=offline-signin')),
    'no ?shot=offline-signin check');
  for (const t of DAPP.tests.filter((x) => x.path.includes('shot=offline'))) {
    assert.ok(t.expectSelector || t.expectText, `${t.name} asserts nothing`);
  }
});
