// Offline session boot + the visible offline state (#1021).
//
// The reported symptom was that reloading the app on a bad connection
// signed the user out: /api/auth/me threw, boot treated that exactly like
// a 401, and the landing page appeared. Nothing on screen said "offline" —
// the amber strip is in normal flow and the auth screens are opaque
// `fixed inset-0 z-40` overlays painted straight over it — so the only
// available reading was "I've been logged out", and the sign-in form the
// user then reached could not possibly succeed.
//
// The suite has no DOM, so the UI layers are pinned the way the rest of
// the shell tests pin theirs: by asserting on stable source tokens. That
// is deliberately shallow, but it catches the failure that actually
// happened here — a piece of the chain being dropped or renamed so the
// offline state stops being reachable end to end.
//
// Run with: node --test tests/offline-session-boot.test.js

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const PUBLIC = path.join(__dirname, '..', 'public');
const read = (rel) => fs.readFileSync(path.join(PUBLIC, rel), 'utf8');

const APP = read('js/app.js');
// The connectivity engine is React-side since #1078 retired /js/offline.js;
// its behaviour is unchanged and this file still asserts against it.
const OFFLINE = fs.readFileSync(
  path.join(__dirname, '..', 'frontend', 'src', 'lib', 'offline.ts'), 'utf8',
);
const AUTH = read('js/auth-screens.js');
const SETTINGS = read('js/settings.js');
const HOME = read('js/home.js');
const CSS = read('css/app.css');
const HTML = read('index.html');
// Copy assertions below match against DECODED text. public/index.html is
// generated by the React shell build now, and React escapes an apostrophe to
// &#x27; — so `You're offline` is present on screen but absent from the raw
// bytes. Decoding compares what the user actually reads.
const { decodeEntities } = require('./helpers/html-tokens');
const DAPP = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', 'dapp.json'), 'utf8'
));

// Body of a top-level App method, from its name to the next method at the
// same indent. Good enough to keep assertions from matching a token that
// lives somewhere else entirely in a 4000-line file.
function appMethod(name) {
  let start = APP.indexOf(`\n  ${name}(`);
  if (start === -1) start = APP.indexOf(`\n  async ${name}(`);
  assert.ok(start > -1, `App.${name} not found`);
  const rest = APP.slice(start + 3);
  const end = rest.search(/\n  \},\n/);
  return rest.slice(0, end === -1 ? rest.length : end);
}

// ── The durable session snapshot ─────────────────────────────────────

test('the snapshot is versioned, age-bounded and written on sign-in', () => {
  assert.match(APP, /SESSION_SNAPSHOT_KEY:\s*'usernode\.session\.v1'/);
  assert.match(APP, /SESSION_SNAPSHOT_MAX_AGE_MS:/);
  // enterAuthed is the one place a session becomes real, so it is the one
  // place the snapshot is written.
  assert.match(appMethod('enterAuthed'), /saveSessionSnapshot\(App\.user\)/);
});

test('reading a snapshot rejects one that has aged out', () => {
  const body = appMethod('readSessionSnapshot');
  assert.match(body, /SESSION_SNAPSHOT_MAX_AGE_MS/);
  assert.match(body, /clearSessionSnapshot\(\)/);
});

test('every snapshot access tolerates a hostile localStorage', () => {
  // Private mode / quota / disabled storage must degrade to "no offline
  // session", never throw out of boot.
  for (const name of ['saveSessionSnapshot', 'readSessionSnapshot', 'clearSessionSnapshot']) {
    assert.match(appMethod(name), /try\s*\{/, `App.${name} has no try/catch`);
  }
});

test('the snapshot is display-only — it is never treated as a credential', () => {
  // Nothing may read the snapshot to decide what the user is ALLOWED to
  // do; the cookie stays the sole credential and the server stays the
  // sole judge. The only consumers are the boot screen choice and the
  // reconcile that replaces it.
  const uses = [...APP.matchAll(/App\.readSessionSnapshot\(\)/g)];
  assert.equal(uses.length, 1, 'the snapshot should be read exactly once, at boot');
  assert.ok(!/snapshot[^\n]*isAdmin|isAdmin[^\n]*snapshot/i.test(APP),
    'no privilege decision may be derived from the snapshot');
});

// ── Three-outcome boot ───────────────────────────────────────────────

test('boot distinguishes "server said no" from "server said nothing"', () => {
  const init = appMethod('init');
  // Answered-not-ok: authoritative sign-out, drop every cached trace.
  assert.match(init, /_dropCachedSession\(\)/);
  // Never answered: fall back to the snapshot rather than the landing page.
  assert.match(init, /readSessionSnapshot\(\)/);
  assert.match(init, /_sessionFromSnapshot = true/);
  assert.match(init, /enterAuthed\(snap\.user\)/);
});

test('the boot session check has a deadline', () => {
  // Without it, a stalled-but-open socket holds boot forever — the white
  // screen half of the bug — even when a snapshot is sitting right there.
  assert.match(APP, /BOOT_SESSION_TIMEOUT_MS:\s*\d+/);
  const body = appMethod('_fetchSession');
  assert.match(body, /AbortController/);
  assert.match(body, /BOOT_SESSION_TIMEOUT_MS/);
  assert.match(body, /clearTimeout/);
});

test('the stale boot comment claiming a login-screen offline guard is gone', () => {
  // It described behaviour that did not exist and was part of why the gap
  // went unnoticed. The guard exists now (see below) — the comment must
  // not be the only thing asserting it.
  assert.ok(!/login screen refuses submits while offline/.test(APP));
});

test('a snapshot boot skips the calls that can only fail offline', () => {
  const body = appMethod('enterAuthed');
  assert.match(body, /if \(!App\._sessionFromSnapshot\) App\.connectEvents\(\)/);
  assert.match(body, /!App\._sessionFromSnapshot && window\.Kudos/);
  assert.match(body, /!App\._sessionFromSnapshot && window\.AiCredit/);
});

test('reconnecting reconciles the snapshot against the real session', () => {
  const body = appMethod('_reconcileSession');
  // 401 → the session really ended.
  assert.match(body, /_dropCachedSession\(\)/);
  // A different user → the shell was painted for someone else.
  assert.match(body, /String\(user\.id\) !== String\(App\.user\?\.id\)/);
  assert.match(body, /location\.reload\(\)/);
  // Same user → promote to a live session.
  assert.match(body, /_sessionFromSnapshot = false/);
  assert.match(body, /App\.connectEvents\(\)/);
  assert.match(body, /resyncCurrentView\(\)/);
  // ...and it is actually wired to the connectivity event.
  assert.match(APP, /usernode:offline-change[\s\S]{0,200}_reconcileSession/);
});

test('every way out of a session clears the snapshot', () => {
  // Leaving it behind would let the next offline boot paint a signed-in
  // shell for an account that logged out — a worse bug than the original.
  assert.match(SETTINGS, /clearSessionSnapshot/);
  assert.match(AUTH, /clearSessionSnapshot/);
  // Including the waiting-room logout, which does not go through settings.
  const waitingLogout = AUTH.slice(AUTH.indexOf("byId('waiting-logout')"));
  assert.match(waitingLogout.slice(0, 500), /clearSessionSnapshot/);
});

// ── The visible offline state ────────────────────────────────────────

test('offline state is published as a body class', () => {
  assert.match(OFFLINE, /classList\.toggle\('is-offline', offline\)/);
});

test('the offline strip outranks the auth overlays and the drawer', () => {
  const rule = CSS.slice(CSS.indexOf('body.is-offline #offline-banner'));
  assert.match(rule.slice(0, 400), /position:\s*fixed/);
  const z = /z-index:\s*(\d+)/.exec(rule.slice(0, 400));
  assert.ok(z, 'the strip has no z-index');
  // Auth overlays are z-40, the drawer panel z-50. Anything at or below
  // those and the strip is invisible exactly when it matters most.
  assert.ok(Number(z[1]) > 50, `z-index ${z[1]} is not above the drawer`);
  // Its space is reserved, so it floats over nothing it would hide.
  assert.match(CSS, /body\.is-offline\s*\{[^}]*padding-top/);
});

test('.offline-only blocks are inert until offline', () => {
  const base = CSS.slice(CSS.indexOf('\n.offline-only {'));
  assert.match(base.slice(0, 120), /display:\s*none/);
  assert.match(CSS, /body\.is-offline \.offline-only \{[^}]*display:\s*block/);
});

test('offline-disabled controls are both greyed and click-proof', () => {
  const rule = CSS.slice(CSS.indexOf('body.is-offline [data-offline-disabled]'));
  assert.match(rule.slice(0, 300), /opacity/);
  assert.match(rule.slice(0, 300), /pointer-events:\s*none/);
});

test('the login screen explains the offline state and gates its controls', () => {
  const screen = HTML.slice(
    HTML.indexOf('id="auth-login-screen"'),
    HTML.indexOf('id="auth-register-screen"')
  );
  const copy = decodeEntities(screen);
  assert.match(screen, /class="offline-only/);
  assert.match(copy, /You're offline/);
  assert.match(screen, /data-offline-retry/);
  // Every control that performs a credential exchange.
  for (const id of ['btn-wallet-sign-in', 'btn-otp-request', 'btn-otp-verify',
    'btn-otp-set-password', 'btn-otp-resend']) {
    const tag = screen.slice(screen.indexOf(`id="${id}"`));
    assert.match(tag.slice(0, 160), /data-offline-disabled/, `${id} is not gated`);
  }
  // ...and the password form's own submit.
  assert.match(screen, /<button type="submit" data-offline-disabled/);
});

test('the landing screen explains the offline state too', () => {
  const screen = HTML.slice(
    HTML.indexOf('id="auth-landing-screen"'),
    HTML.indexOf('id="auth-login-screen"')
  );
  const copy = decodeEntities(screen);
  assert.match(screen, /class="offline-only/);
  assert.match(copy, /You're offline/);
  // Joining the waitlist is a POST; it cannot work offline either.
  const cta = screen.slice(screen.indexOf('id="landing-waitlist-cta"'));
  assert.match(cta.slice(0, 200), /data-offline-disabled/);
});

test('"Try again" is wired once, globally, and re-probes', () => {
  assert.match(OFFLINE, /\[data-offline-retry\]/);
  // lastIndexOf, not indexOf — the module header explains the delegation
  // before the code does it.
  const handler = OFFLINE.slice(OFFLINE.lastIndexOf("closest('[data-offline-retry]')"));
  assert.match(handler.slice(0, 300), /void probe\(\)/);
  // Delegated from the document, so a screen that was hidden when its own
  // module ran still gets a working button.
  assert.match(OFFLINE, /document\.addEventListener\('click'/);
});

test('every credential exchange refuses to submit while offline', () => {
  assert.match(AUTH, /function blockedOffline\(/);
  // The guard consults the /health probe, not navigator.onLine, which
  // false-positives behind exactly the captive portals that break logins.
  const guard = AUTH.slice(AUTH.indexOf('function blockedOffline('));
  assert.match(guard.slice(0, 900), /Offline\.isOffline\(\)/);
  assert.ok(!/navigator\.onLine/.test(guard.slice(0, 900)));
  // One guard per submit path: password, otp request/verify/set-password,
  // wallet, register.
  const uses = [...AUTH.matchAll(/if \(blockedOffline\(/g)];
  assert.ok(uses.length >= 6, `only ${uses.length} submit paths are guarded`);
});

test('home says "offline", not "failed", when the feed cannot load', () => {
  const cat = HOME.slice(HOME.indexOf('Failed to load apps') - 1500);
  assert.match(cat, /Offline\.isOffline\(\)/);
  assert.match(cat, /You're offline/);
  // The generic red failure copy is still there for real failures.
  assert.match(HOME, /Failed to load apps/);
});

// ── Screenshot deep links ────────────────────────────────────────────

test('the offline shots pin connectivity instead of reading it', () => {
  // Capture runners and reviewers always have a working network, so
  // without this the offline UI is unphotographable and the before/after
  // comparison can never be produced.
  const body = appMethod('_applyOfflineShot');
  assert.match(body, /'offline'/);
  assert.match(body, /'offline-signin'/);
  assert.match(body, /Offline\?\.forceOffline\(\)/);
  assert.match(APP, /_applyOfflineShot\(\) === 'offline-signin'/);
  // forceOffline pins the state so a later probe cannot flip it back.
  assert.match(OFFLINE, /export function forceOffline\(\)/);
  assert.match(OFFLINE, /if \(forced\) return/);
});

test('both offline shots are registered as dapp.json checks', () => {
  const paths = DAPP.tests.map((t) => t.path);
  assert.ok(paths.some((p) => p.includes('shot=offline&') || /shot=offline(#|$)/.test(p)),
    'no ?shot=offline check');
  assert.ok(paths.some((p) => p.includes('shot=offline-signin')),
    'no ?shot=offline-signin check');
  for (const t of DAPP.tests.filter((x) => x.path.includes('shot=offline'))) {
    assert.ok(t.expectSelector || t.expectText, `${t.name} asserts nothing`);
  }
});
