// Freshness and lifecycle of the React shell's image-generated artifacts.
//
// public/index.html and public/shell/assets/shell.js are generated by every
// image build. Root tests materialize an ignored HTML copy in pretest because
// many dependency-light structural tests consume the rendered markup.
//
// These tests keep that local fixture fresh and pin the lifecycle that makes
// both artifacts safe to leave untracked.
//
// Run with: node --test tests/shell-build.test.js

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const {
  expectedStamp, readHtmlStamp, HTML_OUTPUT,
} = require('../scripts/shell-stamp');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, HTML_OUTPUT), 'utf8');

const REMEDY = 'Run `npm run ensure:shell`; never commit the generated output.';

test('pretest generated index.html from the current frontend sources', () => {
  const stamped = readHtmlStamp(html);
  assert.ok(
    stamped,
    `${HTML_OUTPUT} has no shell-build stamp in its <head> — it was hand-edited or written by `
    + `something other than the build. ${REMEDY}`,
  );
  const { stamp, files } = expectedStamp();
  assert.equal(
    stamped, stamp,
    `${HTML_OUTPUT} is STALE (built from different sources than the ${files.length} shell input `
    + `files that currently exist). ${REMEDY}`,
  );
});

test('the generated index.html is a plausible shell document, not a stub', () => {
  assert.ok(
    html.length > 80000,
    `${HTML_OUTPUT} is only ${html.length} bytes — the prerender produced an empty or partial tree.`,
  );
  assert.ok(html.includes('GENERATED FILE — DO NOT EDIT'),
    `${HTML_OUTPUT} should carry the do-not-edit banner the build writes`);
  assert.ok(html.includes('id="home-screen"'), 'the home screen is missing from the generated markup');
  assert.ok(html.includes('id="app-view"'), 'the app view is missing from the generated markup');
});

// ── Adjacent text children ─────────────────────────────────────────────
//
// The prerender uses renderToStaticMarkup, which omits the `<!-- -->` markers
// React writes between two adjacent text children — and main.tsx hydrates that
// document, where the pair has already been parsed as ONE text node. React
// calls that a mismatch: error #418, a console.error on EVERY route, which
// fails the platform's proposal checks. #1082 chunk E shipped one for exactly
// one build before the browser caught it (`<span>…</span>{' '}` followed by a
// sentence, in the admin view-only banner), which is why there are guards now.
//
// The authoritative one is in the build: it renders the same tree a second time
// with renderToString and refuses to write the artifact if any separator comes
// out. That needs the frontend workspace installed, so the two tests below add
// a net that does not: one keeps the gate itself from being removed, the other
// looks for the idiom in the sources directly.
const buildScript = fs.readFileSync(path.join(ROOT, 'frontend', 'scripts', 'build-shell.mjs'), 'utf8');
const prerenderSrc = fs.readFileSync(path.join(ROOT, 'frontend', 'src', 'prerender.tsx'), 'utf8');
const viteConfig = fs.readFileSync(path.join(ROOT, 'frontend', 'vite.config.ts'), 'utf8');
const dockerfile = fs.readFileSync(path.join(ROOT, 'Dockerfile'), 'utf8');

test('the build still gates on adjacent text children', () => {
  assert.match(
    prerenderSrc, /renderToString/,
    'frontend/src/prerender.tsx must keep exporting a renderToString probe alongside the '
    + 'renderToStaticMarkup render — it is what makes an unhydratable text pair visible.',
  );
  assert.match(
    prerenderSrc, /export function renderShellWithSeparators/,
    'the probe export build-shell.mjs imports is gone or renamed',
  );
  assert.match(
    buildScript, /renderShellWithSeparators\(\)/,
    'frontend/scripts/build-shell.mjs must call the separator probe',
  );
  assert.match(
    buildScript, /<!-- -->/,
    'frontend/scripts/build-shell.mjs must still look for `<!-- -->` in the probe output and fail '
    + 'the build on it. Without this gate a hydration mismatch reaches every route silently.',
  );
});

test('no shell source renders a bare whitespace expression between text runs', () => {
  // Redundant with the build gate on purpose: this one runs in the root
  // workspace, where frontend/node_modules need not exist.
  const roots = [path.join(ROOT, 'frontend', 'src'), path.join(ROOT, 'frontend', '@')];
  const files = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.(tsx|jsx)$/.test(entry.name)) files.push(full);
    }
  };
  roots.filter((d) => fs.existsSync(d)).forEach(walk);
  assert.ok(files.length > 20, `only found ${files.length} TSX sources — the walk is wrong`);

  const offenders = [];
  for (const file of files) {
    // Strip comments first: the fix for the original mismatch is documented at
    // the site it happened, and that prose quotes the idiom it forbids.
    const code = fs.readFileSync(file, 'utf8')
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/^[ \t]*\/\/.*$/gm, '');
    code.split('\n').forEach((line, i) => {
      if (/\{\s*(['"]) \1\s*\}/.test(line)) offenders.push(`${path.relative(ROOT, file)}:${i + 1}`);
    });
  }
  assert.deepEqual(
    offenders, [],
    `these lines render a whitespace-only JSX expression, which makes the text around it two `
    + `adjacent children and cannot survive hydration (React #418):\n  ${offenders.join('\n  ')}\n`
    + "Put the space inside the neighbouring string instead — {' word…'} — or interpolate the "
    + 'whole run as one child.',
  );
});

test('Docker builds the shell before Tailwind and copies both outputs into the runtime', () => {
  assert.match(dockerfile, /FROM node:22-alpine AS shell/, 'needs a named shell builder stage');
  assert.match(dockerfile, /COPY frontend\/package\.json frontend\/package-lock\.json \.\//,
    'the shell stage must install the lockfile-pinned frontend dependency tree');
  assert.match(dockerfile, /RUN npm ci(?:\s|$)/, 'the shell stage must install frontend dependencies');
  assert.match(dockerfile, /COPY scripts\/shell-stamp\.js \.\/scripts\/shell-stamp\.js/,
    'the shell builder needs the shared stamp logic');
  assert.match(dockerfile, /RUN node frontend\/scripts\/build-shell\.mjs/,
    'the shell stage must run the real two-pass build');

  const cssStage = dockerfile.indexOf('# Stage 2');
  const cssIndexCopy = dockerfile.indexOf(
    'COPY --from=shell /build/public/index.html ./public/index.html',
  );
  const cssBuild = dockerfile.indexOf('RUN npm run build:css');
  assert.ok(cssStage > -1 && cssIndexCopy > cssStage && cssIndexCopy < cssBuild,
    'Tailwind must scan the freshly prerendered index.html from the shell stage');

  const runtimeStage = dockerfile.indexOf('# Stage 3');
  const sourceCopy = dockerfile.lastIndexOf('COPY . .');
  const runtimeHtmlCopy = dockerfile.lastIndexOf(
    'COPY --from=shell /build/public/index.html ./public/index.html',
  );
  const runtimeJsCopy = dockerfile.indexOf(
    'COPY --from=shell /build/public/shell/assets/shell.js ./public/shell/assets/shell.js',
  );
  assert.ok(runtimeStage > -1 && sourceCopy > runtimeStage,
    'the production-only runtime stage must still copy the application sources');
  assert.ok(runtimeHtmlCopy > sourceCopy && runtimeJsCopy > sourceCopy,
    'generated shell assets must overwrite any ignored local artifacts after COPY . .');

  assert.match(dockerfile,
    /COPY --from=shell \/build\/public\/index\.html \/opt\/usernode-shell-assets\/index\.html/,
    'the image must preserve generated HTML outside the dev public bind mount');
  assert.match(dockerfile,
    /COPY --from=shell \/build\/public\/shell\/assets\/shell\.js \/opt\/usernode-shell-assets\/shell\/assets\/shell\.js/,
    'the image must preserve the generated bundle outside the dev public bind mount');
});

test('the untracked shell keeps its fixed single-chunk, no-CSS build contract', () => {
  assert.match(viteConfig, /emptyOutDir:\s*true/,
    'each image build must clear old shell outputs before emitting the bundle');
  assert.match(viteConfig, /entryFileNames:\s*'assets\/shell\.js'/,
    'the service worker depends on the fixed /shell/assets/shell.js URL');
  assert.match(viteConfig, /inlineDynamicImports:\s*true/,
    'the shell must remain one bundle so SHELL_ASSETS never misses a chunk');
  assert.match(buildScript, /strayCss\.length/,
    'the build must reject CSS imports that would violate the stylesheet cascade');

  const gitignore = fs.readFileSync(path.join(ROOT, '.gitignore'), 'utf8').split(/\r?\n/);
  const dockerignore = fs.readFileSync(path.join(ROOT, '.dockerignore'), 'utf8').split(/\r?\n/);
  assert.ok(gitignore.includes('/public/index.html'),
    'the generated HTML must not be committed');
  assert.ok(gitignore.includes('/public/shell/assets/shell.js'),
    'the generated bundle must not be committed');
  assert.ok(dockerignore.includes('public/index.html'),
    'an ignored local HTML artifact must not enter the Docker build context');
  assert.ok(dockerignore.includes('public/shell/assets/shell.js'),
    'an ignored local bundle must not enter the Docker build context');
  assert.ok(dockerignore.includes('**/node_modules'),
    'the local frontend install used by tests must not enter the Docker build context');
});

test('test and native-local entrypoints materialize ignored shell artifacts', () => {
  const packageJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const ensureScript = fs.readFileSync(
    path.join(ROOT, 'scripts', 'ensure-shell-artifacts.js'), 'utf8');
  const compose = fs.readFileSync(path.join(ROOT, 'docker-compose.dev.yml'), 'utf8');

  assert.equal(packageJson.scripts.pretest,
    'node scripts/ensure-shell-artifacts.js --html-only');
  assert.equal(packageJson.scripts.prestart,
    'node scripts/ensure-shell-artifacts.js --runtime');
  assert.equal(packageJson.scripts.predev,
    'node scripts/ensure-shell-artifacts.js --runtime');
  assert.match(ensureScript, /readHtmlStamp/,
    'the local ensure step must rebuild stale HTML, not only missing HTML');
  assert.match(ensureScript, /npm(?:\.cmd)?['"]?\s*:\s*['"]npm['"]|const npm =/,
    'the local ensure step must be able to install the separate frontend workspace');
  assert.match(compose, /node scripts\/restore-image-assets\.js/,
    'dev Compose must restore image-built artifacts hidden by its public bind mount');
});

test('kpack excludes dependency trees from the platform source', () => {
  const project = fs.readFileSync(path.join(ROOT, 'project.toml'), 'utf8');
  assert.match(project, /schema-version = "0\.2"/);
  assert.match(project, /exclude = \[[\s\S]*"node_modules\/"[\s\S]*\]/,
    'a committed dependency tree must not switch Paketo from npm ci to npm rebuild');
});
