import { t as tr, ensureNamespace } from "../../lib/i18n/runtime";
/**
 * The emoji the reaction picker offers (#2387), by category, each with the
 * words its search matches: the Unicode name, plus a few everyday aliases for
 * the ones people reach for (`+1`, `lol`, `tada`, `thanks`).
 *
 * The set and its order are the app chat's grid (public/js/group-chat.js,
 * GRID_REACTIONS), so both surfaces offer the same emoji. No emoji library:
 * the shell loads no cross-origin assets, and a picker needs names, not the
 * several hundred kilobytes of skin tones and sprite sheets a library brings.
 */

export interface EmojiEntry {
  emoji: string;
  /** What a screen reader says for it: "thumbs up". */
  name: string;
  /** Lower-case words the search matches: the name, the Unicode name, aliases. */
  terms: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  emoji: EmojiEntry[];
}

function entries(rows: ReadonlyArray<readonly [string, string, string]>): EmojiEntry[] {
  return rows.map(([emoji, name, terms]) => ({
    emoji, get name() { return tr(name); },
    // Keep English aliases searchable alongside the selected language.
    get terms() { return `${terms} ${tr(name).toLocaleLowerCase()}`; },
  }));
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    get label() { return tr("core:smileys_ba94d3d6"); },
    emoji: entries([
      ['😀', "emoji:grinning_face_51179cd8", 'grinning face'],
      ['😁', "emoji:grinning_face_with_smiling_eyes_491a4956", 'grinning face with smiling eyes'],
      ['😂', "emoji:tears_of_joy_192cb68a", 'face with tears of joy joy laugh lol tears'],
      ['🤣', "emoji:rolling_on_the_floor_laughing_255d81da", 'rolling on the floor laughing rofl rolling laugh'],
      ['😊', "emoji:smiling_face_4552e607", 'smiling face with smiling eyes smile blush happy'],
      ['😇', "emoji:smiling_face_with_halo_a56700af", 'smiling face with halo'],
      ['🙂', "emoji:slightly_smiling_face_abb1d5e2", 'slightly smiling face slight smile'],
      ['😉', "emoji:winking_face_9a18a7e5", 'winking face'],
      ['😍', "emoji:heart_eyes_24b78567", 'smiling face with heart-shaped eyes heart eyes love'],
      ['🥰', "emoji:smiling_face_with_hearts_dc970ab8", 'smiling face with hearts smiling face with smiling eyes and three hearts'],
      ['😘', "emoji:blowing_a_kiss_b56183c7", 'blowing a kiss face throwing a kiss'],
      ['😋', "emoji:face_savouring_delicious_food_edb320fd", 'face savouring delicious food'],
      ['😜', "emoji:face_with_stuck_out_tongue_and_winking_eye_92cceba4", 'face with stuck-out tongue and winking eye'],
      ['🤪', "emoji:grinning_face_with_one_large_and_one_small_eye_770d2bf4", 'grinning face with one large and one small eye'],
      ['😎', "emoji:smiling_face_with_sunglasses_66e336de", 'smiling face with sunglasses cool sunglasses'],
      ['🤓', "emoji:nerd_face_9a12f013", 'nerd face'],
      ['🥳', "emoji:face_with_party_horn_and_party_hat_75f59df1", 'face with party horn and party hat party'],
      ['🤩', "emoji:grinning_face_with_star_eyes_4b7eb54f", 'grinning face with star eyes'],
      ['😏', "emoji:smirking_face_167087ba", 'smirking face'],
      ['😅', "emoji:smiling_face_with_open_mouth_and_cold_sweat_852022e5", 'smiling face with open mouth and cold sweat sweat smile phew'],
      ['😬', "emoji:grimacing_face_0cb51192", 'grimacing face'],
      ['🙃', "emoji:upside_down_face_3a176623", 'upside-down face'],
      ['😌', "emoji:relieved_face_4723fadf", 'relieved face'],
      ['😴', "emoji:sleeping_face_5337169f", 'sleeping face'],
      ['🤤', "emoji:drooling_face_e750be64", 'drooling face'],
      ['😪', "emoji:sleepy_face_48d56bae", 'sleepy face'],
      ['😮', "emoji:face_with_open_mouth_bbbc95b8", 'face with open mouth wow surprised'],
      ['😲', "emoji:astonished_face_e02f2a02", 'astonished face'],
      ['😳', "emoji:flushed_face_8aa99667", 'flushed face'],
      ['🥺', "emoji:face_with_pleading_eyes_fe2a6ce7", 'face with pleading eyes'],
      ['😢', "emoji:crying_face_aa348328", 'crying face sad cry tear'],
      ['😭', "emoji:loudly_crying_face_a7b5419b", 'loudly crying face sob cry'],
      ['😤', "emoji:face_with_look_of_triumph_072dc1c8", 'face with look of triumph'],
      ['😠', "emoji:angry_face_26cdcc9b", 'angry face'],
      ['😡', "emoji:pouting_face_a3ac7834", 'pouting face'],
      ['🤬', "emoji:serious_face_with_symbols_covering_mouth_de87a44a", 'serious face with symbols covering mouth'],
      ['🤯', "emoji:shocked_face_with_exploding_head_9e88b396", 'shocked face with exploding head mind blown exploding head'],
      ['🥵', "emoji:overheated_face_f07e5fb5", 'overheated face'],
      ['🥶', "emoji:freezing_face_f38badb6", 'freezing face'],
      ['😱', "emoji:face_screaming_in_fear_8dc3a001", 'face screaming in fear'],
      ['😨', "emoji:fearful_face_87a1fa4d", 'fearful face'],
      ['😰', "emoji:face_with_open_mouth_and_cold_sweat_6076b7c3", 'face with open mouth and cold sweat'],
      ['🤗', "emoji:hugging_face_e3ce9cc5", 'hugging face'],
      ['🤔', "emoji:thinking_face_181ceb47", 'thinking face thinking hmm'],
      ['🤭', "emoji:smiling_face_with_smiling_eyes_and_hand_covering_3019de58", 'smiling face with smiling eyes and hand covering mouth'],
      ['🤫', "emoji:face_with_finger_covering_closed_lips_a9b672db", 'face with finger covering closed lips'],
      ['🙄', "emoji:face_with_rolling_eyes_20d86233", 'face with rolling eyes eye roll'],
      ['😒', "emoji:unamused_face_fee873b8", 'unamused face'],
      ['😞', "emoji:disappointed_face_9d27ea7d", 'disappointed face'],
      ['😔', "emoji:pensive_face_b2d239f8", 'pensive face'],
      ['😟', "emoji:worried_face_20f8c4fe", 'worried face'],
      ['😕', "emoji:confused_face_1af87ace", 'confused face'],
      ['😖', "emoji:confounded_face_cb469aa2", 'confounded face'],
      ['😫', "emoji:tired_face_9eb6e4f0", 'tired face'],
      ['😩', "emoji:weary_face_28321ba9", 'weary face'],
      ['🤢', "emoji:nauseated_face_540904bd", 'nauseated face'],
      ['🤮', "emoji:face_with_open_mouth_vomiting_047273bf", 'face with open mouth vomiting'],
      ['🤧', "emoji:sneezing_face_8683fdae", 'sneezing face'],
      ['😷', "emoji:face_with_medical_mask_73d95a8f", 'face with medical mask'],
      ['🤒', "emoji:face_with_thermometer_7fd02b0c", 'face with thermometer'],
      ['🤠', "emoji:face_with_cowboy_hat_6f180439", 'face with cowboy hat'],
      ['🤑', "emoji:money_mouth_face_d7ec0e1f", 'money-mouth face'],
      ['😈', "emoji:smiling_face_with_horns_71b7c976", 'smiling face with horns'],
      ['💀', "emoji:skull_8c1a64a5", 'skull skull dead'],
      ['👻', "emoji:ghost_ead6ef03", 'ghost'],
      ['👽', "emoji:extraterrestrial_alien_f1b0f434", 'extraterrestrial alien'],
      ['🤖', "emoji:robot_face_6b3f2bc2", 'robot face'],
      ['💩', "emoji:pile_of_poo_59f28df2", 'pile of poo poop'],
      ['🤡', "emoji:clown_face_67fc2842", 'clown face'],
      ['😺', "emoji:smiling_cat_face_with_open_mouth_ff7b71b3", 'smiling cat face with open mouth'],
      ['🙈', "emoji:see_no_evil_monkey_c5ff7933", 'see-no-evil monkey'],
      ['🙉', "emoji:hear_no_evil_monkey_3ab79e4b", 'hear-no-evil monkey'],
      ['🙊', "emoji:speak_no_evil_monkey_d27d9f27", 'speak-no-evil monkey'],
      ['😶', "emoji:face_without_mouth_43935801", 'face without mouth'],
      ['😐', "emoji:neutral_face_1dfdeab1", 'neutral face'],
      ['🥴', "emoji:face_with_uneven_eyes_and_wavy_mouth_427db147", 'face with uneven eyes and wavy mouth'],
    ]),
  },
  {
    id: 'people',
    get label() { return tr("core:people_hands_f26f3706"); },
    emoji: entries([
      ['👍', "emoji:thumbs_up_d2e2f0f0", 'thumbs up sign thumbs up +1 yes like agree'],
      ['👎', "emoji:thumbs_down_e06ccf9e", 'thumbs down sign thumbs down -1 no dislike'],
      ['👌', "emoji:ok_hand_94e5764c", 'ok hand sign'],
      ['🤌', "emoji:pinched_fingers_d4a268d0", 'pinched fingers'],
      ['✌️', "emoji:victory_hand_3b289ad4", 'victory hand'],
      ['🤞', "emoji:hand_with_index_and_middle_fingers_crossed_2293d569", 'hand with index and middle fingers crossed'],
      ['🤟', "emoji:i_love_you_hand_1414c61e", 'i love you hand sign'],
      ['🤘', "emoji:sign_of_the_horns_673852e2", 'sign of the horns'],
      ['🤙', "emoji:call_me_hand_4876f429", 'call me hand'],
      ['👋', "emoji:waving_hand_4d218df6", 'waving hand sign wave hello hi bye'],
      ['🖐️', "emoji:raised_hand_with_fingers_splayed_47ca5b4e", 'raised hand with fingers splayed'],
      ['✋', "emoji:raised_hand_6756dd0a", 'raised hand'],
      ['👊', "emoji:fisted_hand_c006a65b", 'fisted hand sign'],
      ['✊', "emoji:raised_fist_5d4676e8", 'raised fist'],
      ['🤛', "emoji:left_facing_fist_cb478215", 'left-facing fist'],
      ['🤜', "emoji:right_facing_fist_400f5ead", 'right-facing fist'],
      ['👏', "emoji:clapping_hands_caf52382", 'clapping hands sign clap applause'],
      ['🙌', "emoji:person_raising_both_hands_in_celebration_5528018b", 'person raising both hands in celebration raised hands hooray'],
      ['🤝', "emoji:handshake_dfff30d1", 'handshake handshake deal'],
      ['🙏', "emoji:folded_hands_b19f8bcc", 'person with folded hands pray thanks please folded hands'],
      ['💪', "emoji:flexed_biceps_bbde7691", 'flexed biceps muscle strong flex'],
      ['🖕', "emoji:reversed_hand_with_middle_finger_extended_a0af4c74", 'reversed hand with middle finger extended'],
      ['☝️', "emoji:white_up_pointing_index_8640bca5", 'white up pointing index'],
      ['👆', "emoji:white_up_pointing_backhand_index_cf91bf40", 'white up pointing backhand index'],
      ['👇', "emoji:white_down_pointing_backhand_index_274e6b40", 'white down pointing backhand index'],
      ['👈', "emoji:white_left_pointing_backhand_index_a8d5a45f", 'white left pointing backhand index'],
      ['👉', "emoji:white_right_pointing_backhand_index_79ed09eb", 'white right pointing backhand index'],
      ['✍️', "emoji:writing_hand_816e1f0d", 'writing hand'],
      ['🤲', "emoji:palms_up_together_a02ae584", 'palms up together'],
      ['👀', "emoji:eyes_d8fe183f", 'eyes eyes look'],
      ['🧠', "emoji:brain_bbbf7a64", 'brain'],
      ['🗣️', "emoji:speaking_head_in_silhouette_0276c231", 'speaking head in silhouette'],
      ['💁', "emoji:information_desk_person_2fae6100", 'information desk person'],
      ['🙅', "emoji:face_with_no_good_gesture_3bcc32d0", 'face with no good gesture'],
      ['🙆', "emoji:face_with_ok_gesture_f0d0df77", 'face with ok gesture'],
      ['🤷', "emoji:shrug_3b2c1b50", 'shrug'],
      ['🤦', "emoji:face_palm_97acdfe7", 'face palm'],
      ['🧎', "emoji:kneeling_person_158154f2", 'kneeling person'],
      ['🏃', "emoji:runner_527aa9f4", 'runner'],
      ['💃', "emoji:dancer_bc332d00", 'dancer'],
    ]),
  },
  {
    id: 'hearts',
    get label() { return tr("core:hearts_a061d699"); },
    emoji: entries([
      ['❤️', "emoji:red_heart_c6d2cbde", 'heavy black heart red heart love'],
      ['🧡', "emoji:orange_heart_5d07439f", 'orange heart'],
      ['💛', "emoji:yellow_heart_c22a9216", 'yellow heart'],
      ['💚', "emoji:green_heart_6c4090fa", 'green heart'],
      ['💙', "emoji:blue_heart_21bcfd44", 'blue heart'],
      ['💜', "emoji:purple_heart_80fd3426", 'purple heart'],
      ['🖤', "emoji:black_heart_d961a09c", 'black heart'],
      ['🤍', "emoji:white_heart_5aa0043d", 'white heart'],
      ['🤎', "emoji:brown_heart_6c8e3958", 'brown heart'],
      ['💕', "emoji:two_hearts_1283886a", 'two hearts'],
      ['💞', "emoji:revolving_hearts_40da0de9", 'revolving hearts'],
      ['💓', "emoji:beating_heart_ebc10d6e", 'beating heart'],
      ['💗', "emoji:growing_heart_396a0d9b", 'growing heart'],
      ['💖', "emoji:sparkling_heart_a087c4a4", 'sparkling heart'],
      ['💘', "emoji:heart_with_arrow_bfbd5014", 'heart with arrow'],
      ['💝', "emoji:heart_with_ribbon_46c96562", 'heart with ribbon'],
      ['💔', "emoji:broken_heart_3e2c5b56", 'broken heart'],
      ['❣️', "emoji:heavy_heart_exclamation_mark_ornament_e3f6deeb", 'heavy heart exclamation mark ornament'],
      ['💟', "emoji:heart_decoration_a7942bae", 'heart decoration'],
      ['💌', "emoji:love_letter_220f5261", 'love letter'],
    ]),
  },
  {
    id: 'nature',
    get label() { return tr("core:animals_nature_61106377"); },
    emoji: entries([
      ['🐶', "emoji:dog_face_491ee902", 'dog face'],
      ['🐱', "emoji:cat_face_d03a556d", 'cat face'],
      ['🐭', "emoji:mouse_face_0507215c", 'mouse face'],
      ['🐹', "emoji:hamster_face_32987892", 'hamster face'],
      ['🐰', "emoji:rabbit_face_2cd02d72", 'rabbit face'],
      ['🦊', "emoji:fox_face_e4895eb4", 'fox face'],
      ['🐻', "emoji:bear_face_3170f4fd", 'bear face'],
      ['🐼', "emoji:panda_face_dddf6556", 'panda face'],
      ['🐨', "emoji:koala_c88cf946", 'koala'],
      ['🐯', "emoji:tiger_face_d1746140", 'tiger face'],
      ['🦁', "emoji:lion_face_cf7049e8", 'lion face'],
      ['🐮', "emoji:cow_face_d72efa10", 'cow face'],
      ['🐷', "emoji:pig_face_a7946947", 'pig face'],
      ['🐸', "emoji:frog_face_7253afa9", 'frog face'],
      ['🐵', "emoji:monkey_face_bda45c59", 'monkey face'],
      ['🐔', "emoji:chicken_811eb81b", 'chicken'],
      ['🐧', "emoji:penguin_0a4346f8", 'penguin'],
      ['🐦', "emoji:bird_7a5179ee", 'bird'],
      ['🦆', "emoji:duck_2d2370db", 'duck'],
      ['🦅', "emoji:eagle_e73b48f7", 'eagle'],
      ['🦉', "emoji:owl_10f7127b", 'owl'],
      ['🐢', "emoji:turtle_74dd730b", 'turtle'],
      ['🐍', "emoji:snake_538d7d9f", 'snake'],
      ['🐙', "emoji:octopus_5633c9b8", 'octopus'],
      ['🦀', "emoji:crab_3349a915", 'crab'],
      ['🐬', "emoji:dolphin_532f011e", 'dolphin'],
      ['🐳', "emoji:spouting_whale_28939afb", 'spouting whale'],
      ['🦈', "emoji:shark_31fc1594", 'shark'],
      ['🦋', "emoji:butterfly_fcfd075c", 'butterfly'],
      ['🐝', "emoji:honeybee_30cce014", 'honeybee'],
      ['🐞', "emoji:lady_beetle_d3cfbf48", 'lady beetle'],
      ['🐌', "emoji:snail_62156a7b", 'snail'],
      ['🌸', "emoji:cherry_blossom_aaa40dd4", 'cherry blossom'],
      ['🌹', "emoji:rose_618d663a", 'rose'],
      ['🌻', "emoji:sunflower_8f398886", 'sunflower'],
      ['🌵', "emoji:cactus_caaeac31", 'cactus'],
      ['🌲', "emoji:evergreen_tree_fba885d7", 'evergreen tree'],
      ['🍀', "emoji:four_leaf_clover_5bb934ce", 'four leaf clover'],
      ['🌈', "emoji:rainbow_8fced00b", 'rainbow'],
      ['⭐', "emoji:white_medium_star_06de133d", 'white medium star star'],
      ['🌟', "emoji:glowing_star_a08c01e6", 'glowing star glowing star'],
      ['✨', "emoji:sparkles_dd368cc7", 'sparkles sparkles magic'],
      ['⚡', "emoji:high_voltage_e28a28cd", 'high voltage sign'],
      ['☀️', "emoji:black_sun_with_rays_f63b8caf", 'black sun with rays'],
      ['🌙', "emoji:crescent_moon_c5b7b970", 'crescent moon'],
      ['☁️', "emoji:cloud_56681010", 'cloud'],
      ['🌧️', "emoji:cloud_with_rain_e9a94edd", 'cloud with rain'],
      ['❄️', "emoji:snowflake_de5a1adf", 'snowflake'],
      ['🌊', "emoji:water_wave_f0f6ca11", 'water wave'],
      ['🌍', "emoji:earth_globe_europe_africa_f3d5daab", 'earth globe europe-africa'],
    ]),
  },
  {
    id: 'food',
    get label() { return tr("core:food_drink_48f1e8be"); },
    emoji: entries([
      ['🍎', "emoji:red_apple_510e9cd0", 'red apple'],
      ['🍌', "emoji:banana_b493d483", 'banana'],
      ['🍉', "emoji:watermelon_31a2d528", 'watermelon'],
      ['🍇', "emoji:grapes_8286ee4e", 'grapes'],
      ['🍓', "emoji:strawberry_5e737f89", 'strawberry'],
      ['🍒', "emoji:cherries_c6de72fb", 'cherries'],
      ['🍑', "emoji:peach_85356064", 'peach'],
      ['🥭', "emoji:mango_6815f3c3", 'mango'],
      ['🍍', "emoji:pineapple_b0fef621", 'pineapple'],
      ['🥑', "emoji:avocado_f9c9baac", 'avocado'],
      ['🍅', "emoji:tomato_5ed728c2", 'tomato'],
      ['🥕', "emoji:carrot_b9648229", 'carrot'],
      ['🌽', "emoji:ear_of_maize_5cef97a2", 'ear of maize'],
      ['🍞', "emoji:bread_985604c2", 'bread'],
      ['🧀', "emoji:cheese_wedge_38147ba4", 'cheese wedge'],
      ['🥚', "emoji:egg_34707c3f", 'egg'],
      ['🥓', "emoji:bacon_9cca0703", 'bacon'],
      ['🍔', "emoji:hamburger_cc86d865", 'hamburger'],
      ['🍟', "emoji:french_fries_fbeef318", 'french fries'],
      ['🍕', "emoji:slice_of_pizza_afd16adf", 'slice of pizza'],
      ['🌭', "emoji:hot_dog_836cef5d", 'hot dog'],
      ['🌮', "emoji:taco_07c05679", 'taco'],
      ['🌯', "emoji:burrito_befede35", 'burrito'],
      ['🍣', "emoji:sushi_cf98f59c", 'sushi'],
      ['🍜', "emoji:steaming_bowl_ced397b3", 'steaming bowl'],
      ['🍝', "emoji:spaghetti_9b4c5399", 'spaghetti'],
      ['🍿', "emoji:popcorn_0a4ef253", 'popcorn'],
      ['🍩', "emoji:doughnut_b6f8ff77", 'doughnut'],
      ['🍪', "emoji:cookie_d7e83e28", 'cookie'],
      ['🎂', "emoji:birthday_cake_dcdc548b", 'birthday cake'],
      ['🍰', "emoji:shortcake_a439529b", 'shortcake'],
      ['🧁', "emoji:cupcake_b0eaeafb", 'cupcake'],
      ['🍫', "emoji:chocolate_bar_7a4aa8cd", 'chocolate bar'],
      ['🍬', "emoji:candy_4d1608c8", 'candy'],
      ['🍭', "emoji:lollipop_07307784", 'lollipop'],
      ['☕', "emoji:hot_beverage_4aa0f7b4", 'hot beverage coffee hot beverage tea'],
      ['🍵', "emoji:teacup_without_handle_54deff39", 'teacup without handle'],
      ['🥤', "emoji:cup_with_straw_74c5ee65", 'cup with straw'],
      ['🍺', "emoji:beer_mug_6b607807", 'beer mug beer'],
      ['🍻', "emoji:clinking_beer_mugs_0f12a618", 'clinking beer mugs'],
      ['🥂', "emoji:clinking_glasses_f0b9c908", 'clinking glasses'],
      ['🍷', "emoji:wine_glass_da6ed454", 'wine glass'],
      ['🍸', "emoji:cocktail_glass_1330bbb5", 'cocktail glass'],
      ['🥃', "emoji:tumbler_glass_887170d2", 'tumbler glass'],
    ]),
  },
  {
    id: 'activities',
    get label() { return tr("core:activities_4d0076e6"); },
    emoji: entries([
      ['⚽', "emoji:soccer_ball_9dfb8408", 'soccer ball'],
      ['🏀', "emoji:basketball_and_hoop_833ce973", 'basketball and hoop'],
      ['🏈', "emoji:american_football_f86cc90c", 'american football'],
      ['⚾', "emoji:baseball_a01edad9", 'baseball'],
      ['🎾', "emoji:tennis_racquet_and_ball_9d07f3f2", 'tennis racquet and ball'],
      ['🏐', "emoji:volleyball_3580c926", 'volleyball'],
      ['🎱', "emoji:billiards_0516eecb", 'billiards'],
      ['🏓', "emoji:table_tennis_paddle_and_ball_a9e50aea", 'table tennis paddle and ball'],
      ['🏸', "emoji:badminton_racquet_and_shuttlecock_afdedfb2", 'badminton racquet and shuttlecock'],
      ['🥊', "emoji:boxing_glove_6aaff8c3", 'boxing glove'],
      ['⛳', "emoji:flag_in_hole_f53ac9df", 'flag in hole'],
      ['🎣', "emoji:fishing_pole_and_fish_7a05823b", 'fishing pole and fish'],
      ['🎽', "emoji:running_shirt_with_sash_b19e6eee", 'running shirt with sash'],
      ['⛷️', "emoji:skier_b139bdb6", 'skier'],
      ['🏂', "emoji:snowboarder_71c83de3", 'snowboarder'],
      ['🏆', "emoji:trophy_b39419ef", 'trophy trophy win'],
      ['🥇', "emoji:first_place_medal_34d57013", 'first place medal'],
      ['🥈', "emoji:second_place_medal_5e7c9832", 'second place medal'],
      ['🥉', "emoji:third_place_medal_58012f90", 'third place medal'],
      ['🏅', "emoji:sports_medal_5e7e1445", 'sports medal'],
      ['🎮', "emoji:video_game_1f905c95", 'video game'],
      ['🕹️', "emoji:joystick_39a39d1b", 'joystick'],
      ['🎲', "emoji:game_die_add40ea9", 'game die'],
      ['🧩', "emoji:jigsaw_puzzle_piece_4f181768", 'jigsaw puzzle piece'],
      ['♟️', "emoji:black_chess_pawn_d16f0339", 'black chess pawn'],
      ['🎯', "emoji:direct_hit_57d5d849", 'direct hit target bullseye dart'],
      ['🎳', "emoji:bowling_472de632", 'bowling'],
      ['🎤', "emoji:microphone_d7f4d3cc", 'microphone'],
      ['🎧', "emoji:headphone_458be899", 'headphone'],
      ['🎸', "emoji:guitar_d081f5e4", 'guitar'],
      ['🥁', "emoji:drum_with_drumsticks_ddb14fc1", 'drum with drumsticks'],
      ['🎹', "emoji:musical_keyboard_6e7e4e46", 'musical keyboard'],
      ['🎺', "emoji:trumpet_b7dfa266", 'trumpet'],
      ['🎻', "emoji:violin_00e3e584", 'violin'],
      ['🎬', "emoji:clapper_board_f91a7c24", 'clapper board'],
      ['🎨', "emoji:artist_palette_8a7f97e0", 'artist palette'],
      ['🎭', "emoji:performing_arts_8395c7f1", 'performing arts'],
      ['🎪', "emoji:circus_tent_e2824454", 'circus tent'],
      ['🎟️', "emoji:admission_tickets_5e9adeed", 'admission tickets'],
      ['🎰', "emoji:slot_machine_219035c2", 'slot machine'],
    ]),
  },
  {
    id: 'objects',
    get label() { return tr("core:travel_objects_78e213fc"); },
    emoji: entries([
      ['🚀', "emoji:rocket_c58dd0a3", 'rocket rocket ship launch'],
      ['✈️', "emoji:airplane_0f488683", 'airplane'],
      ['🚗', "emoji:automobile_f4c7ec93", 'automobile'],
      ['🚕', "emoji:taxi_12796d3d", 'taxi'],
      ['🚌', "emoji:bus_04e027e4", 'bus'],
      ['🚲', "emoji:bicycle_d29af8a2", 'bicycle'],
      ['🛴', "emoji:scooter_b5ad1213", 'scooter'],
      ['🏍️', "emoji:racing_motorcycle_fc87a629", 'racing motorcycle'],
      ['🚂', "emoji:steam_locomotive_11ca3229", 'steam locomotive'],
      ['🚢', "emoji:ship_e5d5b971", 'ship'],
      ['⛵', "emoji:sailboat_72bec4bd", 'sailboat'],
      ['🗺️', "emoji:world_map_1282d2d0", 'world map'],
      ['🏠', "emoji:house_building_04aa629f", 'house building'],
      ['🏖️', "emoji:beach_with_umbrella_ad52bb7c", 'beach with umbrella'],
      ['🏔️', "emoji:snow_capped_mountain_3a6ba58c", 'snow capped mountain'],
      ['🗽', "emoji:statue_of_liberty_9b5ffe6d", 'statue of liberty'],
      ['💻', "emoji:personal_computer_4be4d566", 'personal computer'],
      ['🖥️', "emoji:desktop_computer_8abbbcb0", 'desktop computer'],
      ['⌨️', "emoji:keyboard_91f060a9", 'keyboard'],
      ['🖱️', "emoji:three_button_mouse_3b599a53", 'three button mouse'],
      ['📱', "emoji:mobile_phone_c339fb77", 'mobile phone'],
      ['📷', "emoji:camera_89e8b951", 'camera'],
      ['🎥', "emoji:movie_camera_7c9009ce", 'movie camera'],
      ['📺', "emoji:television_a031eda2", 'television'],
      ['📻', "emoji:radio_aa3a05d9", 'radio'],
      ['⏰', "emoji:alarm_clock_26869f79", 'alarm clock'],
      ['⌚', "emoji:watch_baed8316", 'watch'],
      ['🔋', "emoji:battery_f3d1701e", 'battery'],
      ['🔌', "emoji:electric_plug_94dbb6b8", 'electric plug'],
      ['💡', "emoji:electric_light_bulb_ce5f36cb", 'electric light bulb idea bulb'],
      ['🔦', "emoji:electric_torch_0b5a8e8f", 'electric torch'],
      ['🕯️', "emoji:candle_6fa599fe", 'candle'],
      ['🛠️', "emoji:hammer_and_wrench_1f4223ea", 'hammer and wrench'],
      ['🔧', "emoji:wrench_702b023f", 'wrench'],
      ['🔨', "emoji:hammer_3ef81cb1", 'hammer'],
      ['⚙️', "emoji:gear_70ad3de5", 'gear'],
      ['🧲', "emoji:magnet_ed05dd4d", 'magnet'],
      ['🔑', "emoji:key_2c70e12b", 'key'],
      ['🔒', "emoji:lock_0c030586", 'lock'],
      ['🔓', "emoji:open_lock_a3b9f0c9", 'open lock'],
      ['📌', "emoji:pushpin_e5c0c206", 'pushpin'],
      ['📎', "emoji:paperclip_670d47cc", 'paperclip'],
      ['✂️', "emoji:black_scissors_3b0be9fc", 'black scissors'],
      ['📏', "emoji:straight_ruler_b4ab1e97", 'straight ruler'],
      ['📚', "emoji:books_6e317bcd", 'books'],
      ['📖', "emoji:open_book_0d7e35c4", 'open book'],
      ['📝', "emoji:memo_9c225a95", 'memo'],
      ['✏️', "emoji:pencil_13809668", 'pencil'],
      ['📦', "emoji:package_bc4a7118", 'package'],
      ['🎁', "emoji:wrapped_present_68d6e76c", 'wrapped present'],
      ['🎈', "emoji:balloon_00477ad8", 'balloon'],
      ['🎉', "emoji:party_popper_22d85374", 'party popper party tada celebrate'],
      ['🎊', "emoji:confetti_ball_96fdfb8f", 'confetti ball'],
      ['🛒', "emoji:shopping_trolley_1fa7f302", 'shopping trolley'],
      ['💰', "emoji:money_bag_ab2d39d7", 'money bag'],
      ['💵', "emoji:banknote_with_dollar_cade82fd", 'banknote with dollar sign'],
      ['💳', "emoji:credit_card_c59faf33", 'credit card'],
      ['💎', "emoji:gem_stone_1c9189df", 'gem stone'],
    ]),
  },
  {
    id: 'symbols',
    get label() { return tr("core:symbols_9491fc41"); },
    emoji: entries([
      ['✅', "emoji:check_mark_6f144cb4", 'white heavy check mark check done yes ok'],
      ['☑️', "emoji:ballot_box_with_check_1317853a", 'ballot box with check'],
      ['❌', "emoji:cross_mark_69bc932f", 'cross mark x no cross wrong'],
      ['❎', "emoji:negative_squared_cross_mark_bef1caab", 'negative squared cross mark'],
      ['⚠️', "emoji:warning_4bd9354b", 'warning sign warning caution'],
      ['🚫', "emoji:no_entry_d99f230e", 'no entry sign'],
      ['❗', "emoji:heavy_exclamation_mark_ed40fd6f", 'heavy exclamation mark symbol'],
      ['❓', "emoji:black_question_mark_ornament_0cc9b383", 'black question mark ornament'],
      ['‼️', "emoji:double_exclamation_mark_3c35c37d", 'double exclamation mark'],
      ['⁉️', "emoji:exclamation_question_mark_56dc2a42", 'exclamation question mark'],
      ['💯', "emoji:hundred_points_2ce8d56d", 'hundred points symbol 100 hundred perfect'],
      ['🔥', "emoji:fire_dc9f28b1", 'fire fire lit hot'],
      ['💥', "emoji:collision_9550e70a", 'collision symbol'],
      ['💫', "emoji:dizzy_d810e252", 'dizzy symbol'],
      ['💢', "emoji:anger_d4cc56aa", 'anger symbol'],
      ['💤', "emoji:sleeping_546f04bb", 'sleeping symbol'],
      ['💬', "emoji:speech_balloon_1c612430", 'speech balloon'],
      ['💭', "emoji:thought_balloon_91cd1ba8", 'thought balloon'],
      ['🗨️', "emoji:left_speech_bubble_ae57f594", 'left speech bubble'],
      ['🔔', "emoji:bell_f683740c", 'bell'],
      ['🔕', "emoji:bell_with_cancellation_stroke_6a31839a", 'bell with cancellation stroke'],
      ['🎵', "emoji:musical_note_5462f625", 'musical note'],
      ['🎶', "emoji:multiple_musical_notes_ea77a05c", 'multiple musical notes'],
      ['➕', "emoji:heavy_plus_c6d0f09e", 'heavy plus sign'],
      ['➖', "emoji:heavy_minus_382c53fb", 'heavy minus sign'],
      ['➗', "emoji:heavy_division_b7bdcb6b", 'heavy division sign'],
      ['✖️', "emoji:heavy_multiplication_x_a7faa431", 'heavy multiplication x'],
      ['♾️', "emoji:permanent_paper_b33e172b", 'permanent paper sign'],
      ['💲', "emoji:heavy_dollar_fb7195ba", 'heavy dollar sign'],
      ['©️', "emoji:copyright_c2fca2aa", 'copyright sign'],
      ['®️', "emoji:registered_b1a9e561", 'registered sign'],
      ['™️', "emoji:trade_mark_20febcfd", 'trade mark sign'],
      ['🔴', "emoji:large_red_circle_c12e5a8e", 'large red circle'],
      ['🟠', "emoji:large_orange_circle_ada766ed", 'large orange circle'],
      ['🟡', "emoji:large_yellow_circle_058b5e7e", 'large yellow circle'],
      ['🟢', "emoji:large_green_circle_b70f5d20", 'large green circle'],
      ['🔵', "emoji:large_blue_circle_992aee78", 'large blue circle'],
      ['🟣', "emoji:large_purple_circle_778fe653", 'large purple circle'],
      ['⚫', "emoji:medium_black_circle_8feae6c2", 'medium black circle'],
      ['⚪', "emoji:medium_white_circle_10ab0032", 'medium white circle'],
      ['🔺', "emoji:up_pointing_red_triangle_8e1e9922", 'up-pointing red triangle'],
      ['🔻', "emoji:down_pointing_red_triangle_32a5a36e", 'down-pointing red triangle'],
      ['🔄', "emoji:anticlockwise_downwards_and_upwards_open_circle__cf62d529", 'anticlockwise downwards and upwards open circle arrows'],
      ['🔁', "emoji:clockwise_rightwards_and_leftwards_open_circle_a_0d675928", 'clockwise rightwards and leftwards open circle arrows'],
      ['▶️', "emoji:black_right_pointing_triangle_d1b698c5", 'black right-pointing triangle'],
      ['⏸️', "emoji:double_vertical_bar_16f73532", 'double vertical bar'],
      ['⏩', "emoji:black_right_pointing_double_triangle_78f3a2e7", 'black right-pointing double triangle'],
      ['⏪', "emoji:black_left_pointing_double_triangle_e6c52d07", 'black left-pointing double triangle'],
      ['🆗', "emoji:squared_ok_3d34f65e", 'squared ok'],
      ['🆒', "emoji:squared_cool_dc012c0e", 'squared cool'],
      ['🆕', "emoji:squared_new_a4eef358", 'squared new'],
      ['🆓', "emoji:squared_free_d68991a8", 'squared free'],
      ['🔝', "emoji:top_with_upwards_arrow_above_4cc1f2c5", 'top with upwards arrow above'],
      ['🔚', "emoji:end_with_leftwards_arrow_above_89e136b8", 'end with leftwards arrow above'],
      ['🔜', "emoji:soon_with_rightwards_arrow_above_c6afc2ad", 'soon with rightwards arrow above'],
      ['🏁', "emoji:chequered_flag_15395f4e", 'chequered flag'],
      ['🚩', "emoji:triangular_flag_on_post_5cdc19ad", 'triangular flag on post red flag'],
      ['🏳️', "emoji:waving_white_flag_eecfe9c5", 'waving white flag'],
      ['🏴', "emoji:waving_black_flag_33961b28", 'waving black flag'],
      ['🐛', "emoji:bug_ecb53f36", 'bug bug'],
    ]),
  },
];

/** Every emoji once, for search and for naming a recent one. */
export const ALL_EMOJI: readonly EmojiEntry[] = (() => {
  const seen = new Set<string>();
  const all: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emoji) {
      if (seen.has(entry.emoji)) continue;
      seen.add(entry.emoji);
      all.push(entry);
    }
  }
  return all;
})();

const BY_EMOJI = new Map(ALL_EMOJI.map((entry) => [entry.emoji, entry]));

/** The spoken name of an emoji, for an aria-label: "thumbs up". */
export function emojiName(emoji: string): string {
  if (typeof window !== 'undefined') void ensureNamespace('emoji').catch(() => {});
  return BY_EMOJI.get(emoji)?.name || emoji;
}

/**
 * The emoji whose terms contain every word of the query, in picker order.
 * An empty query matches nothing: the picker shows its categories instead.
 */
export function searchEmoji(query: string, limit = 64): EmojiEntry[] {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const hits: EmojiEntry[] = [];
  for (const entry of ALL_EMOJI) {
    if (words.every((word) => entry.terms.includes(word))) hits.push(entry);
    if (hits.length >= limit) break;
  }
  return hits;
}
