/**
 * The emoji the reaction picker offers (#2387), by category, each with the
 * words its search matches: the Unicode name, plus a few everyday aliases for
 * the ones people reach for (`+1`, `lol`, `tada`, `thanks`).
 *
 * The set and its order are the app chat's grid (public/js/group-chat.js,
 * GRID_REACTIONS), so both surfaces offer the same emoji. No emoji library:
 * the shell loads no cross-origin assets, and a picker needs names, not the
 * several hundred kilobytes of skin tones and sprite sheets a library brings.
 */

export interface EmojiEntry {
  emoji: string;
  /** What a screen reader says for it: "thumbs up". */
  name: string;
  /** Lower-case words the search matches: the name, the Unicode name, aliases. */
  terms: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  emoji: EmojiEntry[];
}

function entries(rows: ReadonlyArray<readonly [string, string, string]>): EmojiEntry[] {
  return rows.map(([emoji, name, terms]) => ({ emoji, name, terms }));
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emoji: entries([
      ['😀', 'grinning face', 'grinning face'],
      ['😁', 'grinning face with smiling eyes', 'grinning face with smiling eyes'],
      ['😂', 'tears of joy', 'face with tears of joy joy laugh lol tears'],
      ['🤣', 'rolling on the floor laughing', 'rolling on the floor laughing rofl rolling laugh'],
      ['😊', 'smiling face', 'smiling face with smiling eyes smile blush happy'],
      ['😇', 'smiling face with halo', 'smiling face with halo'],
      ['🙂', 'slightly smiling face', 'slightly smiling face slight smile'],
      ['😉', 'winking face', 'winking face'],
      ['😍', 'heart eyes', 'smiling face with heart-shaped eyes heart eyes love'],
      ['🥰', 'smiling face with hearts', 'smiling face with hearts smiling face with smiling eyes and three hearts'],
      ['😘', 'blowing a kiss', 'blowing a kiss face throwing a kiss'],
      ['😋', 'face savouring delicious food', 'face savouring delicious food'],
      ['😜', 'face with stuck-out tongue and winking eye', 'face with stuck-out tongue and winking eye'],
      ['🤪', 'grinning face with one large and one small eye', 'grinning face with one large and one small eye'],
      ['😎', 'smiling face with sunglasses', 'smiling face with sunglasses cool sunglasses'],
      ['🤓', 'nerd face', 'nerd face'],
      ['🥳', 'face with party horn and party hat', 'face with party horn and party hat party'],
      ['🤩', 'grinning face with star eyes', 'grinning face with star eyes'],
      ['😏', 'smirking face', 'smirking face'],
      ['😅', 'smiling face with open mouth and cold sweat', 'smiling face with open mouth and cold sweat sweat smile phew'],
      ['😬', 'grimacing face', 'grimacing face'],
      ['🙃', 'upside-down face', 'upside-down face'],
      ['😌', 'relieved face', 'relieved face'],
      ['😴', 'sleeping face', 'sleeping face'],
      ['🤤', 'drooling face', 'drooling face'],
      ['😪', 'sleepy face', 'sleepy face'],
      ['😮', 'face with open mouth', 'face with open mouth wow surprised'],
      ['😲', 'astonished face', 'astonished face'],
      ['😳', 'flushed face', 'flushed face'],
      ['🥺', 'face with pleading eyes', 'face with pleading eyes'],
      ['😢', 'crying face', 'crying face sad cry tear'],
      ['😭', 'loudly crying face', 'loudly crying face sob cry'],
      ['😤', 'face with look of triumph', 'face with look of triumph'],
      ['😠', 'angry face', 'angry face'],
      ['😡', 'pouting face', 'pouting face'],
      ['🤬', 'serious face with symbols covering mouth', 'serious face with symbols covering mouth'],
      ['🤯', 'shocked face with exploding head', 'shocked face with exploding head mind blown exploding head'],
      ['🥵', 'overheated face', 'overheated face'],
      ['🥶', 'freezing face', 'freezing face'],
      ['😱', 'face screaming in fear', 'face screaming in fear'],
      ['😨', 'fearful face', 'fearful face'],
      ['😰', 'face with open mouth and cold sweat', 'face with open mouth and cold sweat'],
      ['🤗', 'hugging face', 'hugging face'],
      ['🤔', 'thinking face', 'thinking face thinking hmm'],
      ['🤭', 'smiling face with smiling eyes and hand covering mouth', 'smiling face with smiling eyes and hand covering mouth'],
      ['🤫', 'face with finger covering closed lips', 'face with finger covering closed lips'],
      ['🙄', 'face with rolling eyes', 'face with rolling eyes eye roll'],
      ['😒', 'unamused face', 'unamused face'],
      ['😞', 'disappointed face', 'disappointed face'],
      ['😔', 'pensive face', 'pensive face'],
      ['😟', 'worried face', 'worried face'],
      ['😕', 'confused face', 'confused face'],
      ['😖', 'confounded face', 'confounded face'],
      ['😫', 'tired face', 'tired face'],
      ['😩', 'weary face', 'weary face'],
      ['🤢', 'nauseated face', 'nauseated face'],
      ['🤮', 'face with open mouth vomiting', 'face with open mouth vomiting'],
      ['🤧', 'sneezing face', 'sneezing face'],
      ['😷', 'face with medical mask', 'face with medical mask'],
      ['🤒', 'face with thermometer', 'face with thermometer'],
      ['🤠', 'face with cowboy hat', 'face with cowboy hat'],
      ['🤑', 'money-mouth face', 'money-mouth face'],
      ['😈', 'smiling face with horns', 'smiling face with horns'],
      ['💀', 'skull', 'skull skull dead'],
      ['👻', 'ghost', 'ghost'],
      ['👽', 'extraterrestrial alien', 'extraterrestrial alien'],
      ['🤖', 'robot face', 'robot face'],
      ['💩', 'pile of poo', 'pile of poo poop'],
      ['🤡', 'clown face', 'clown face'],
      ['😺', 'smiling cat face with open mouth', 'smiling cat face with open mouth'],
      ['🙈', 'see-no-evil monkey', 'see-no-evil monkey'],
      ['🙉', 'hear-no-evil monkey', 'hear-no-evil monkey'],
      ['🙊', 'speak-no-evil monkey', 'speak-no-evil monkey'],
      ['😶', 'face without mouth', 'face without mouth'],
      ['😐', 'neutral face', 'neutral face'],
      ['🥴', 'face with uneven eyes and wavy mouth', 'face with uneven eyes and wavy mouth'],
    ]),
  },
  {
    id: 'people',
    label: 'People & hands',
    emoji: entries([
      ['👍', 'thumbs up', 'thumbs up sign thumbs up +1 yes like agree'],
      ['👎', 'thumbs down', 'thumbs down sign thumbs down -1 no dislike'],
      ['👌', 'ok hand', 'ok hand sign'],
      ['🤌', 'pinched fingers', 'pinched fingers'],
      ['✌️', 'victory hand', 'victory hand'],
      ['🤞', 'hand with index and middle fingers crossed', 'hand with index and middle fingers crossed'],
      ['🤟', 'i love you hand', 'i love you hand sign'],
      ['🤘', 'sign of the horns', 'sign of the horns'],
      ['🤙', 'call me hand', 'call me hand'],
      ['👋', 'waving hand', 'waving hand sign wave hello hi bye'],
      ['🖐️', 'raised hand with fingers splayed', 'raised hand with fingers splayed'],
      ['✋', 'raised hand', 'raised hand'],
      ['👊', 'fisted hand', 'fisted hand sign'],
      ['✊', 'raised fist', 'raised fist'],
      ['🤛', 'left-facing fist', 'left-facing fist'],
      ['🤜', 'right-facing fist', 'right-facing fist'],
      ['👏', 'clapping hands', 'clapping hands sign clap applause'],
      ['🙌', 'person raising both hands in celebration', 'person raising both hands in celebration raised hands hooray'],
      ['🤝', 'handshake', 'handshake handshake deal'],
      ['🙏', 'folded hands', 'person with folded hands pray thanks please folded hands'],
      ['💪', 'flexed biceps', 'flexed biceps muscle strong flex'],
      ['🖕', 'reversed hand with middle finger extended', 'reversed hand with middle finger extended'],
      ['☝️', 'white up pointing index', 'white up pointing index'],
      ['👆', 'white up pointing backhand index', 'white up pointing backhand index'],
      ['👇', 'white down pointing backhand index', 'white down pointing backhand index'],
      ['👈', 'white left pointing backhand index', 'white left pointing backhand index'],
      ['👉', 'white right pointing backhand index', 'white right pointing backhand index'],
      ['✍️', 'writing hand', 'writing hand'],
      ['🤲', 'palms up together', 'palms up together'],
      ['👀', 'eyes', 'eyes eyes look'],
      ['🧠', 'brain', 'brain'],
      ['🗣️', 'speaking head in silhouette', 'speaking head in silhouette'],
      ['💁', 'information desk person', 'information desk person'],
      ['🙅', 'face with no good gesture', 'face with no good gesture'],
      ['🙆', 'face with ok gesture', 'face with ok gesture'],
      ['🤷', 'shrug', 'shrug'],
      ['🤦', 'face palm', 'face palm'],
      ['🧎', 'kneeling person', 'kneeling person'],
      ['🏃', 'runner', 'runner'],
      ['💃', 'dancer', 'dancer'],
    ]),
  },
  {
    id: 'hearts',
    label: 'Hearts',
    emoji: entries([
      ['❤️', 'red heart', 'heavy black heart red heart love'],
      ['🧡', 'orange heart', 'orange heart'],
      ['💛', 'yellow heart', 'yellow heart'],
      ['💚', 'green heart', 'green heart'],
      ['💙', 'blue heart', 'blue heart'],
      ['💜', 'purple heart', 'purple heart'],
      ['🖤', 'black heart', 'black heart'],
      ['🤍', 'white heart', 'white heart'],
      ['🤎', 'brown heart', 'brown heart'],
      ['💕', 'two hearts', 'two hearts'],
      ['💞', 'revolving hearts', 'revolving hearts'],
      ['💓', 'beating heart', 'beating heart'],
      ['💗', 'growing heart', 'growing heart'],
      ['💖', 'sparkling heart', 'sparkling heart'],
      ['💘', 'heart with arrow', 'heart with arrow'],
      ['💝', 'heart with ribbon', 'heart with ribbon'],
      ['💔', 'broken heart', 'broken heart'],
      ['❣️', 'heavy heart exclamation mark ornament', 'heavy heart exclamation mark ornament'],
      ['💟', 'heart decoration', 'heart decoration'],
      ['💌', 'love letter', 'love letter'],
    ]),
  },
  {
    id: 'nature',
    label: 'Animals & nature',
    emoji: entries([
      ['🐶', 'dog face', 'dog face'],
      ['🐱', 'cat face', 'cat face'],
      ['🐭', 'mouse face', 'mouse face'],
      ['🐹', 'hamster face', 'hamster face'],
      ['🐰', 'rabbit face', 'rabbit face'],
      ['🦊', 'fox face', 'fox face'],
      ['🐻', 'bear face', 'bear face'],
      ['🐼', 'panda face', 'panda face'],
      ['🐨', 'koala', 'koala'],
      ['🐯', 'tiger face', 'tiger face'],
      ['🦁', 'lion face', 'lion face'],
      ['🐮', 'cow face', 'cow face'],
      ['🐷', 'pig face', 'pig face'],
      ['🐸', 'frog face', 'frog face'],
      ['🐵', 'monkey face', 'monkey face'],
      ['🐔', 'chicken', 'chicken'],
      ['🐧', 'penguin', 'penguin'],
      ['🐦', 'bird', 'bird'],
      ['🦆', 'duck', 'duck'],
      ['🦅', 'eagle', 'eagle'],
      ['🦉', 'owl', 'owl'],
      ['🐢', 'turtle', 'turtle'],
      ['🐍', 'snake', 'snake'],
      ['🐙', 'octopus', 'octopus'],
      ['🦀', 'crab', 'crab'],
      ['🐬', 'dolphin', 'dolphin'],
      ['🐳', 'spouting whale', 'spouting whale'],
      ['🦈', 'shark', 'shark'],
      ['🦋', 'butterfly', 'butterfly'],
      ['🐝', 'honeybee', 'honeybee'],
      ['🐞', 'lady beetle', 'lady beetle'],
      ['🐌', 'snail', 'snail'],
      ['🌸', 'cherry blossom', 'cherry blossom'],
      ['🌹', 'rose', 'rose'],
      ['🌻', 'sunflower', 'sunflower'],
      ['🌵', 'cactus', 'cactus'],
      ['🌲', 'evergreen tree', 'evergreen tree'],
      ['🍀', 'four leaf clover', 'four leaf clover'],
      ['🌈', 'rainbow', 'rainbow'],
      ['⭐', 'white medium star', 'white medium star star'],
      ['🌟', 'glowing star', 'glowing star glowing star'],
      ['✨', 'sparkles', 'sparkles sparkles magic'],
      ['⚡', 'high voltage', 'high voltage sign'],
      ['☀️', 'black sun with rays', 'black sun with rays'],
      ['🌙', 'crescent moon', 'crescent moon'],
      ['☁️', 'cloud', 'cloud'],
      ['🌧️', 'cloud with rain', 'cloud with rain'],
      ['❄️', 'snowflake', 'snowflake'],
      ['🌊', 'water wave', 'water wave'],
      ['🌍', 'earth globe europe-africa', 'earth globe europe-africa'],
    ]),
  },
  {
    id: 'food',
    label: 'Food & drink',
    emoji: entries([
      ['🍎', 'red apple', 'red apple'],
      ['🍌', 'banana', 'banana'],
      ['🍉', 'watermelon', 'watermelon'],
      ['🍇', 'grapes', 'grapes'],
      ['🍓', 'strawberry', 'strawberry'],
      ['🍒', 'cherries', 'cherries'],
      ['🍑', 'peach', 'peach'],
      ['🥭', 'mango', 'mango'],
      ['🍍', 'pineapple', 'pineapple'],
      ['🥑', 'avocado', 'avocado'],
      ['🍅', 'tomato', 'tomato'],
      ['🥕', 'carrot', 'carrot'],
      ['🌽', 'ear of maize', 'ear of maize'],
      ['🍞', 'bread', 'bread'],
      ['🧀', 'cheese wedge', 'cheese wedge'],
      ['🥚', 'egg', 'egg'],
      ['🥓', 'bacon', 'bacon'],
      ['🍔', 'hamburger', 'hamburger'],
      ['🍟', 'french fries', 'french fries'],
      ['🍕', 'slice of pizza', 'slice of pizza'],
      ['🌭', 'hot dog', 'hot dog'],
      ['🌮', 'taco', 'taco'],
      ['🌯', 'burrito', 'burrito'],
      ['🍣', 'sushi', 'sushi'],
      ['🍜', 'steaming bowl', 'steaming bowl'],
      ['🍝', 'spaghetti', 'spaghetti'],
      ['🍿', 'popcorn', 'popcorn'],
      ['🍩', 'doughnut', 'doughnut'],
      ['🍪', 'cookie', 'cookie'],
      ['🎂', 'birthday cake', 'birthday cake'],
      ['🍰', 'shortcake', 'shortcake'],
      ['🧁', 'cupcake', 'cupcake'],
      ['🍫', 'chocolate bar', 'chocolate bar'],
      ['🍬', 'candy', 'candy'],
      ['🍭', 'lollipop', 'lollipop'],
      ['☕', 'hot beverage', 'hot beverage coffee hot beverage tea'],
      ['🍵', 'teacup without handle', 'teacup without handle'],
      ['🥤', 'cup with straw', 'cup with straw'],
      ['🍺', 'beer mug', 'beer mug beer'],
      ['🍻', 'clinking beer mugs', 'clinking beer mugs'],
      ['🥂', 'clinking glasses', 'clinking glasses'],
      ['🍷', 'wine glass', 'wine glass'],
      ['🍸', 'cocktail glass', 'cocktail glass'],
      ['🥃', 'tumbler glass', 'tumbler glass'],
    ]),
  },
  {
    id: 'activities',
    label: 'Activities',
    emoji: entries([
      ['⚽', 'soccer ball', 'soccer ball'],
      ['🏀', 'basketball and hoop', 'basketball and hoop'],
      ['🏈', 'american football', 'american football'],
      ['⚾', 'baseball', 'baseball'],
      ['🎾', 'tennis racquet and ball', 'tennis racquet and ball'],
      ['🏐', 'volleyball', 'volleyball'],
      ['🎱', 'billiards', 'billiards'],
      ['🏓', 'table tennis paddle and ball', 'table tennis paddle and ball'],
      ['🏸', 'badminton racquet and shuttlecock', 'badminton racquet and shuttlecock'],
      ['🥊', 'boxing glove', 'boxing glove'],
      ['⛳', 'flag in hole', 'flag in hole'],
      ['🎣', 'fishing pole and fish', 'fishing pole and fish'],
      ['🎽', 'running shirt with sash', 'running shirt with sash'],
      ['⛷️', 'skier', 'skier'],
      ['🏂', 'snowboarder', 'snowboarder'],
      ['🏆', 'trophy', 'trophy trophy win'],
      ['🥇', 'first place medal', 'first place medal'],
      ['🥈', 'second place medal', 'second place medal'],
      ['🥉', 'third place medal', 'third place medal'],
      ['🏅', 'sports medal', 'sports medal'],
      ['🎮', 'video game', 'video game'],
      ['🕹️', 'joystick', 'joystick'],
      ['🎲', 'game die', 'game die'],
      ['🧩', 'jigsaw puzzle piece', 'jigsaw puzzle piece'],
      ['♟️', 'black chess pawn', 'black chess pawn'],
      ['🎯', 'direct hit', 'direct hit target bullseye dart'],
      ['🎳', 'bowling', 'bowling'],
      ['🎤', 'microphone', 'microphone'],
      ['🎧', 'headphone', 'headphone'],
      ['🎸', 'guitar', 'guitar'],
      ['🥁', 'drum with drumsticks', 'drum with drumsticks'],
      ['🎹', 'musical keyboard', 'musical keyboard'],
      ['🎺', 'trumpet', 'trumpet'],
      ['🎻', 'violin', 'violin'],
      ['🎬', 'clapper board', 'clapper board'],
      ['🎨', 'artist palette', 'artist palette'],
      ['🎭', 'performing arts', 'performing arts'],
      ['🎪', 'circus tent', 'circus tent'],
      ['🎟️', 'admission tickets', 'admission tickets'],
      ['🎰', 'slot machine', 'slot machine'],
    ]),
  },
  {
    id: 'objects',
    label: 'Travel & objects',
    emoji: entries([
      ['🚀', 'rocket', 'rocket rocket ship launch'],
      ['✈️', 'airplane', 'airplane'],
      ['🚗', 'automobile', 'automobile'],
      ['🚕', 'taxi', 'taxi'],
      ['🚌', 'bus', 'bus'],
      ['🚲', 'bicycle', 'bicycle'],
      ['🛴', 'scooter', 'scooter'],
      ['🏍️', 'racing motorcycle', 'racing motorcycle'],
      ['🚂', 'steam locomotive', 'steam locomotive'],
      ['🚢', 'ship', 'ship'],
      ['⛵', 'sailboat', 'sailboat'],
      ['🗺️', 'world map', 'world map'],
      ['🏠', 'house building', 'house building'],
      ['🏖️', 'beach with umbrella', 'beach with umbrella'],
      ['🏔️', 'snow capped mountain', 'snow capped mountain'],
      ['🗽', 'statue of liberty', 'statue of liberty'],
      ['💻', 'personal computer', 'personal computer'],
      ['🖥️', 'desktop computer', 'desktop computer'],
      ['⌨️', 'keyboard', 'keyboard'],
      ['🖱️', 'three button mouse', 'three button mouse'],
      ['📱', 'mobile phone', 'mobile phone'],
      ['📷', 'camera', 'camera'],
      ['🎥', 'movie camera', 'movie camera'],
      ['📺', 'television', 'television'],
      ['📻', 'radio', 'radio'],
      ['⏰', 'alarm clock', 'alarm clock'],
      ['⌚', 'watch', 'watch'],
      ['🔋', 'battery', 'battery'],
      ['🔌', 'electric plug', 'electric plug'],
      ['💡', 'electric light bulb', 'electric light bulb idea bulb'],
      ['🔦', 'electric torch', 'electric torch'],
      ['🕯️', 'candle', 'candle'],
      ['🛠️', 'hammer and wrench', 'hammer and wrench'],
      ['🔧', 'wrench', 'wrench'],
      ['🔨', 'hammer', 'hammer'],
      ['⚙️', 'gear', 'gear'],
      ['🧲', 'magnet', 'magnet'],
      ['🔑', 'key', 'key'],
      ['🔒', 'lock', 'lock'],
      ['🔓', 'open lock', 'open lock'],
      ['📌', 'pushpin', 'pushpin'],
      ['📎', 'paperclip', 'paperclip'],
      ['✂️', 'black scissors', 'black scissors'],
      ['📏', 'straight ruler', 'straight ruler'],
      ['📚', 'books', 'books'],
      ['📖', 'open book', 'open book'],
      ['📝', 'memo', 'memo'],
      ['✏️', 'pencil', 'pencil'],
      ['📦', 'package', 'package'],
      ['🎁', 'wrapped present', 'wrapped present'],
      ['🎈', 'balloon', 'balloon'],
      ['🎉', 'party popper', 'party popper party tada celebrate'],
      ['🎊', 'confetti ball', 'confetti ball'],
      ['🛒', 'shopping trolley', 'shopping trolley'],
      ['💰', 'money bag', 'money bag'],
      ['💵', 'banknote with dollar', 'banknote with dollar sign'],
      ['💳', 'credit card', 'credit card'],
      ['💎', 'gem stone', 'gem stone'],
    ]),
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emoji: entries([
      ['✅', 'check mark', 'white heavy check mark check done yes ok'],
      ['☑️', 'ballot box with check', 'ballot box with check'],
      ['❌', 'cross mark', 'cross mark x no cross wrong'],
      ['❎', 'negative squared cross mark', 'negative squared cross mark'],
      ['⚠️', 'warning', 'warning sign warning caution'],
      ['🚫', 'no entry', 'no entry sign'],
      ['❗', 'heavy exclamation mark', 'heavy exclamation mark symbol'],
      ['❓', 'black question mark ornament', 'black question mark ornament'],
      ['‼️', 'double exclamation mark', 'double exclamation mark'],
      ['⁉️', 'exclamation question mark', 'exclamation question mark'],
      ['💯', 'hundred points', 'hundred points symbol 100 hundred perfect'],
      ['🔥', 'fire', 'fire fire lit hot'],
      ['💥', 'collision', 'collision symbol'],
      ['💫', 'dizzy', 'dizzy symbol'],
      ['💢', 'anger', 'anger symbol'],
      ['💤', 'sleeping', 'sleeping symbol'],
      ['💬', 'speech balloon', 'speech balloon'],
      ['💭', 'thought balloon', 'thought balloon'],
      ['🗨️', 'left speech bubble', 'left speech bubble'],
      ['🔔', 'bell', 'bell'],
      ['🔕', 'bell with cancellation stroke', 'bell with cancellation stroke'],
      ['🎵', 'musical note', 'musical note'],
      ['🎶', 'multiple musical notes', 'multiple musical notes'],
      ['➕', 'heavy plus', 'heavy plus sign'],
      ['➖', 'heavy minus', 'heavy minus sign'],
      ['➗', 'heavy division', 'heavy division sign'],
      ['✖️', 'heavy multiplication x', 'heavy multiplication x'],
      ['♾️', 'permanent paper', 'permanent paper sign'],
      ['💲', 'heavy dollar', 'heavy dollar sign'],
      ['©️', 'copyright', 'copyright sign'],
      ['®️', 'registered', 'registered sign'],
      ['™️', 'trade mark', 'trade mark sign'],
      ['🔴', 'large red circle', 'large red circle'],
      ['🟠', 'large orange circle', 'large orange circle'],
      ['🟡', 'large yellow circle', 'large yellow circle'],
      ['🟢', 'large green circle', 'large green circle'],
      ['🔵', 'large blue circle', 'large blue circle'],
      ['🟣', 'large purple circle', 'large purple circle'],
      ['⚫', 'medium black circle', 'medium black circle'],
      ['⚪', 'medium white circle', 'medium white circle'],
      ['🔺', 'up-pointing red triangle', 'up-pointing red triangle'],
      ['🔻', 'down-pointing red triangle', 'down-pointing red triangle'],
      ['🔄', 'anticlockwise downwards and upwards open circle arrows', 'anticlockwise downwards and upwards open circle arrows'],
      ['🔁', 'clockwise rightwards and leftwards open circle arrows', 'clockwise rightwards and leftwards open circle arrows'],
      ['▶️', 'black right-pointing triangle', 'black right-pointing triangle'],
      ['⏸️', 'double vertical bar', 'double vertical bar'],
      ['⏩', 'black right-pointing double triangle', 'black right-pointing double triangle'],
      ['⏪', 'black left-pointing double triangle', 'black left-pointing double triangle'],
      ['🆗', 'squared ok', 'squared ok'],
      ['🆒', 'squared cool', 'squared cool'],
      ['🆕', 'squared new', 'squared new'],
      ['🆓', 'squared free', 'squared free'],
      ['🔝', 'top with upwards arrow above', 'top with upwards arrow above'],
      ['🔚', 'end with leftwards arrow above', 'end with leftwards arrow above'],
      ['🔜', 'soon with rightwards arrow above', 'soon with rightwards arrow above'],
      ['🏁', 'chequered flag', 'chequered flag'],
      ['🚩', 'triangular flag on post', 'triangular flag on post red flag'],
      ['🏳️', 'waving white flag', 'waving white flag'],
      ['🏴', 'waving black flag', 'waving black flag'],
      ['🐛', 'bug', 'bug bug'],
    ]),
  },
];

/** Every emoji once, for search and for naming a recent one. */
export const ALL_EMOJI: readonly EmojiEntry[] = (() => {
  const seen = new Set<string>();
  const all: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emoji) {
      if (seen.has(entry.emoji)) continue;
      seen.add(entry.emoji);
      all.push(entry);
    }
  }
  return all;
})();

const BY_EMOJI = new Map(ALL_EMOJI.map((entry) => [entry.emoji, entry]));

/** The spoken name of an emoji, for an aria-label: "thumbs up". */
export function emojiName(emoji: string): string {
  return BY_EMOJI.get(emoji)?.name || emoji;
}

/**
 * The emoji whose terms contain every word of the query, in picker order.
 * An empty query matches nothing: the picker shows its categories instead.
 */
export function searchEmoji(query: string, limit = 64): EmojiEntry[] {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const hits: EmojiEntry[] = [];
  for (const entry of ALL_EMOJI) {
    if (words.every((word) => entry.terms.includes(word))) hits.push(entry);
    if (hits.length >= limit) break;
  }
  return hits;
}
