#!/usr/bin/env node
// Builds the platform shell's two generated artifacts:
//
//   public/shell/assets/shell.js   the React runtime + shell tree; ignored
//                                  locally and generated by every image build
//   public/index.html              the document Express serves at /; ignored
//                                  locally and generated by every image build
//
// Run from the repo root as `npm run build:shell` (or from frontend/ as
// `npm run build`) for local browser work. Both outputs are checkout-local;
// Docker always rebuilds them from the lockfile-pinned sources.
//
// ── Two passes ─────────────────────────────────────────────────────────
//
//   1. CLIENT — `vite build` bundles src/main.tsx into the unhashed
//      single-chunk /shell/assets/shell.js.
//   2. SSG — `vite build --ssr` bundles src/prerender.tsx for Node, which is
//      then imported and called to render the shell tree to static markup.
//
// The document is composed here rather than by Vite's HTML pipeline. That is
// the point: src/head.html is carried over byte-for-byte, so the head's
// blocking scripts, the `.in-native-webview` inline script, the cascade
// self-check probe and the native.css → app.css → tailwind.css link order all
// survive untouched. Nothing rewrites them, so nothing can silently reorder
// them.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const dirname = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND = path.join(dirname, '..');
const ROOT = path.join(FRONTEND, '..');

const {
  expectedStamp, formatHtmlStamp, formatJsStamp, formatBuildMeta, normalizeBuildSha,
  buildScopedAssetUrl, prefixShellAssetUrls,
  HTML_OUTPUT, JS_OUTPUT,
} = require(path.join(ROOT, 'scripts', 'shell-stamp.js'));

function fail(message) {
  console.error(`[build-shell] ${message}`);
  process.exit(1);
}

function resolveViteCli() {
  let pkgJson;
  try {
    pkgJson = require.resolve('vite/package.json', { paths: [FRONTEND] });
  } catch {
    fail('vite is not installed. Run `npm install` inside frontend/ first.');
  }
  const pkg = JSON.parse(fs.readFileSync(pkgJson, 'utf8'));
  const binRel = typeof pkg.bin === 'string' ? pkg.bin : pkg.bin && pkg.bin.vite;
  if (!binRel) fail(`Could not find the vite CLI entry point in ${pkgJson}`);
  return path.join(path.dirname(pkgJson), binRel);
}

const vite = resolveViteCli();

function runVite(args) {
  try {
    execFileSync(process.execPath, [vite, ...args], { cwd: FRONTEND, stdio: ['ignore', 'inherit', 'inherit'] });
  } catch (err) {
    fail(`vite ${args.join(' ')} failed: ${err.message}`);
  }
}

// ── Pass 1: the browser bundle ─────────────────────────────────────────
console.log('[build-shell] pass 1/2 — client bundle');
runVite(['build']);

const jsPath = path.join(ROOT, JS_OUTPUT);
if (!fs.existsSync(jsPath)) fail(`the client build did not emit ${JS_OUTPUT}`);

// Nothing in the shell tree imports CSS today (shadcn components are Tailwind
// classes in TSX and the shell's stylesheet is the existing compiled v3
// build). An emitted stylesheet therefore means something pulled in CSS of
// its own and the document would need a FOURTH <link> — which would land
// after /css/tailwind.css and break the cascade contract the head asserts.
// Fail loudly rather than ship a silently restyled shell.
const emittedAssets = fs.readdirSync(path.join(ROOT, 'public', 'shell', 'assets'));
const strayCss = emittedAssets.filter((f) => f.endsWith('.css'));
if (strayCss.length) {
  fail(
    `the client build emitted a stylesheet (${strayCss.join(', ')}). The shell gets ALL of its `
    + 'CSS from the existing compiled /css/tailwind.css; something under frontend/ now imports '
    + 'its own CSS. Remove that import rather than adding a fourth <link> — see the cascade '
    + 'note in frontend/src/head.html.',
  );
}

// ── Pass 2: prerender the shell tree ───────────────────────────────────
console.log('[build-shell] pass 2/2 — SSG prerender');
const ssrDir = path.join(FRONTEND, '.ssr');
fs.rmSync(ssrDir, { recursive: true, force: true });
runVite(['build', '--config', 'vite.ssr.config.ts', '--logLevel', 'warn']);

const ssrEntry = path.join(ssrDir, 'prerender.js');
if (!fs.existsSync(ssrEntry)) fail(`the SSR build did not emit ${path.relative(ROOT, ssrEntry)}`);

const { renderShell, renderShellWithSeparators } = await import(pathToFileURL(ssrEntry).href);
const markup = renderShell();
if (!markup || markup.length < 10000) {
  fail(`renderShell() produced only ${markup ? markup.length : 0} bytes — the shell tree looks empty.`);
}

// ── Hydration-safety gate: no adjacent text children ───────────────────
//
// renderToStaticMarkup drops the `<!-- -->` separators React writes between
// two adjacent text children; main.tsx then hydrates that document, where the
// pair has been parsed as ONE text node. React calls that a mismatch (#418) —
// a console.error on EVERY route, which fails the platform's proposal checks.
// The idiom that causes it is ordinary and easy to write by accident:
//
//     <span>Label</span>{' '}                     ← two adjacent text children
//     Sentence that follows.
//
// The fix is always to make it one child: put the whitespace inside the string
// ({' Sentence that follows.'}) or interpolate the whole run.
//
// renderToString over the same tree emits the separators, so its output is an
// exact locator rather than a source heuristic. Refuse to write the artifact.
const probe = renderShellWithSeparators();
const separators = probe.split('<!-- -->').length - 1;
if (separators > 0) {
  const at = probe.indexOf('<!-- -->');
  const context = probe.slice(Math.max(0, at - 220), at + 120).replace(/\s+/g, ' ');
  fail(
    `the shell tree has ${separators} pair(s) of ADJACENT TEXT CHILDREN, which cannot survive `
    + 'hydration: the prerendered document merges each pair into one text node and React logs a '
    + `mismatch (error #418) on every route. First one is here:\n\n    …${context}…\n\n`
    + "Find the component rendering that text and make it a SINGLE child — move the whitespace "
    + "inside the string ({' word…'}) instead of using a bare {' '} between two text runs.",
  );
}

// ── Compose the document ───────────────────────────────────────────────
const head = fs.readFileSync(path.join(FRONTEND, 'src', 'head.html'), 'utf8');

// The <body> element's own attributes live here, not in Shell.tsx: React
// hydrates body's CHILDREN, so the element itself is the template's. This is
// the flex column every screen's height depends on
// (`flex flex-col` + `height:100dvh` with `flex-1` <main> children).
// The page GROUND. `bg-white` until the widget-language reskin: the shell was
// white-on-white and drew its structure with borders. The language in the design
// screenshots separates by FIGURE/GROUND instead — white cards floating on a
// light grey page — so the ground moves to the neutral ramp's `zinc-100` and the
// ~97 existing `bg-white` surfaces become the cards, with no class edits at those
// call sites. Dark mode already had a distinct ground and is unchanged in ROLE
// (only its hex moved, in tailwind.config.js).
const BODY_ATTRS = 'class="bg-zinc-100 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 flex flex-col" style="height:100dvh"';

const { stamp, files } = expectedStamp();

// Which platform build this document IS, baked in at generation time. Read
// back by public/js/app.js as its boot baseline — see the header over
// formatBuildMeta in scripts/shell-stamp.js for why a server answer could not
// be one. `dev` outside a deploy, which is what /api/version reports there
// too. Docker's shell stage forwards the GIT_SHA build arg into this process.
//
// It is also what every asset URL below is scoped by. A document built for a
// deploy loads its scripts and stylesheets from `/b/<sha>/…` (the
// "Build-scoped asset URLs" note in scripts/shell-stamp.js), so the server can
// answer them immutable; a `dev` document keeps the plain paths. The head's
// tags are rewritten by prefixShellAssetUrls — a prefix on the path and
// nothing else, so the order and every other attribute survive exactly as
// src/head.html wrote them — and the <script> tags at the end of <body> come
// out of the prerender already scoped, through frontend/src/lib/asset-url.ts
// reading this same GIT_SHA.
const buildSha = normalizeBuildSha(process.env.GIT_SHA);

// The entry is the LAST thing in <head> and a module, therefore deferred:
// it runs after the 47 classic <script> tags at the end of <body> and before
// DOMContentLoaded. See the header comment in src/main.tsx for why that
// window is the only correct place for it.
const entryTag = '  <!-- React shell entry. A deferred module on purpose: it hydrates AFTER the\n'
  + '       legacy /js/** scripts at the end of <body> have defined their globals and\n'
  + '       BEFORE DOMContentLoaded runs their init()s. frontend/src/main.tsx explains\n'
  + '       why that ordering — and the flushSync around hydration — is load-bearing. -->\n'
  + `  <script type="module" src="${buildScopedAssetUrl('/shell/assets/shell.js', buildSha)}"></script>\n`;

// NO `class="dark"` ON <html>. It was hardcoded here, which made the document
// the service worker precaches a DARK document for everybody: the theme is a
// per-viewer decision (localStorage, else the OS preference) and the only
// thing that can make it is the head-blocking module in src/head.html, which
// adds or removes the class before first paint. Asserting one in the artifact
// meant every reader of the cached file that runs BEFORE that module — a
// stylesheet keyed on `.dark`, the critical background rule in that same head,
// a WebView that defers scripts, anything rendering the document without
// running it — got dark as the answer whatever the viewer had chosen. The
// module is unchanged and still decides; the artifact just stops guessing.
const html = `<!DOCTYPE html>
<html lang="en">
<head>
  ${formatHtmlStamp(stamp)}
  ${formatBuildMeta(buildSha)}
  <!-- GENERATED FILE — DO NOT EDIT.
       Built from frontend/ by \`npm run build:shell\`; the markup lives in
       frontend/src/Shell.tsx and this <head> in frontend/src/head.html.
       Hand edits here are overwritten by the next build. -->
${prefixShellAssetUrls(head, buildSha).replace(/\s*$/, '\n')}${entryTag}</head>
<body ${BODY_ATTRS}>${markup}</body>
</html>
`;
// NOTE the absence of newlines around ${markup}. main.tsx hydrates
// document.body, so body's child list must be EXACTLY what <Shell/> renders.
// A newline after the <body> tag is a text node React does not expect as the
// first child, which is a hydration mismatch — React error #418, logged as a
// console.error, which fails the platform's proposal checks on every route.
// (renderToStaticMarkup emits no inter-element whitespace of its own, so the
// markup is already a clean element sequence.)

fs.writeFileSync(path.join(ROOT, HTML_OUTPUT), html);

// Stamp the JS too so a running image can identify the exact source set that
// produced it. The image copies HTML and JS from this same builder invocation.
const js = fs.readFileSync(jsPath, 'utf8').replace(/^﻿/, '');
fs.writeFileSync(jsPath, `${formatJsStamp(stamp)}\n${js}`);

fs.rmSync(ssrDir, { recursive: true, force: true });

console.log(`[build-shell] wrote ${HTML_OUTPUT} (${html.length} bytes) and ${JS_OUTPUT} (${js.length} bytes)`);
console.log(`[build-shell] stamped ${stamp.slice(0, 16)}… over ${files.length} input files`);
console.log(`[build-shell] platform build id: ${buildSha}${buildSha === 'dev' ? ' (plain asset paths)' : ' (assets scoped under /b/<sha>/)'}`);
