#!/usr/bin/env node
// Copies the shell's three third-party browser libraries out of
// node_modules into public/vendor/, and regenerates the provenance README.
//
//   npm run vendor:assets
//
// These used to be <script src="https://cdn.jsdelivr.net/…"> tags in
// public/index.html. Serving them from our own origin removes the last
// cross-origin asset requests in the shell, which is what lets the service
// worker precache everything the app needs to render (and keeps QR codes and
// chat markdown working on networks that block jsdelivr).
//
// Filenames carry the version so a bump is a visible rename in review, and
// so a stale copy can never masquerade as the pinned one. The packages stay
// devDependencies: they are build-time inputs, so `npm ci --production`
// never ships a second copy into the runtime image.
//
// Same-origin script tags can't use Subresource Integrity meaningfully, so
// the sha384 digests that used to live in the `integrity` attributes are
// recorded in public/vendor/README.md instead — provenance you can re-verify
// against npm at any time.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'vendor');

// package → { dist file inside the package, vendored filename, what it's for }
const ASSETS = [
  {
    pkg: 'marked',
    version: '15.0.12',
    from: 'marked.min.js',
    to: 'marked-15.0.12.min.js',
    purpose: 'Markdown → HTML for renderMarkdown() in public/js/dev-chat.js (also used by group-chat.js and app-view.js).',
  },
  {
    pkg: 'dompurify',
    version: '3.4.4',
    from: path.join('dist', 'purify.min.js'),
    to: 'purify-3.4.4.min.js',
    purpose: 'Sanitizes that rendered markdown before it reaches innerHTML. Never bypass it.',
  },
  {
    pkg: 'qrcodejs',
    version: '1.0.0',
    from: 'qrcode.min.js',
    to: 'qrcode-1.0.0.min.js',
    purpose: 'Wallet address QR codes (public/js/wallet-sheet.js, public/js/settings.js). npm mirror of davidshimjs/qrcodejs, which the old /gh/ CDN URL served UNPINNED.',
  },
];

function fail(message) {
  console.error(`[vendor-assets] ${message}`);
  process.exit(1);
}

// Resolve the installed package directory by path rather than through
// require.resolve: modern packages (dompurify among them) declare an
// `exports` map that deliberately does NOT expose ./package.json, so
// require.resolve('dompurify/package.json') throws even when it's installed.
function resolvePackageDir(pkg) {
  const dir = path.join(ROOT, 'node_modules', pkg);
  if (!fs.existsSync(path.join(dir, 'package.json'))) {
    return fail(`${pkg} is not installed. Run \`npm install\` (dev dependencies included) first.`);
  }
  return dir;
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const rows = [];
for (const asset of ASSETS) {
  const dir = resolvePackageDir(asset.pkg);
  const installed = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')).version;
  // The vendored filename encodes a version; a mismatch means package.json
  // and this script disagree, and the copy would be mislabelled.
  if (installed !== asset.version) {
    fail(`${asset.pkg} is installed at ${installed} but this script vendors ${asset.version}. `
      + 'Update package.json and the ASSETS table (and the filename) together.');
  }
  const src = path.join(dir, asset.from);
  if (!fs.existsSync(src)) fail(`${asset.pkg}@${installed} has no ${asset.from} — check the package layout.`);

  const bytes = fs.readFileSync(src);
  fs.writeFileSync(path.join(OUT_DIR, asset.to), bytes);
  const sha384 = crypto.createHash('sha384').update(bytes).digest('base64');
  rows.push({ ...asset, installed, sha384, bytes: bytes.length });
  console.log(`[vendor-assets] ${asset.pkg}@${installed} → public/vendor/${asset.to} (${(bytes.length / 1024).toFixed(1)} KB)`);
}

const readme = `# public/vendor — third-party browser libraries, self-hosted

GENERATED by \`npm run vendor:assets\` (scripts/vendor-assets.js). Do not
edit these files by hand: the next run overwrites them, and a hand-patched
copy no longer matches the digest recorded below.

The platform shell used to load all three from \`cdn.jsdelivr.net\`. Serving
them from our own origin means the shell makes **no cross-origin asset
requests at all**, so the service worker can precache everything needed to
render (public/sw.js \`SHELL_ASSETS\`), and QR codes and chat markdown keep
working on networks that block the CDN.

## Provenance

Each file is copied verbatim from the pinned devDependency in the repo root
\`package.json\`. Same-origin \`<script>\` tags can't use Subresource
Integrity, so the sha384 digests that used to live in the \`integrity\`
attributes are recorded here instead — re-verify any row against npm with:

    npm pack <package>@<version>   # then sha384 the dist file

The \`marked\` and \`dompurify\` digests below are **identical to the
\`integrity\` attributes the old jsdelivr tags carried**, i.e. these copies
are byte-for-byte what the CDN was serving. The \`qrcodejs\` digest matches
\`qrcodejs@1.0.0\` on npm — an improvement on the old tag, which pulled an
UNPINNED GitHub ref (\`/gh/davidshimjs/qrcodejs/qrcode.min.js\`) with no
integrity attribute at all.

| File | Package | Version | Source path in package | sha384 (base64) | Size |
|---|---|---|---|---|---|
${rows.map((r) => `| \`${r.to}\` | \`${r.pkg}\` | ${r.installed} | \`${r.from.split(path.sep).join('/')}\` | \`${r.sha384}\` | ${(r.bytes / 1024).toFixed(1)} KB |`).join('\n')}

## What each one is for

${rows.map((r) => `- **${r.to}** — ${r.purpose}`).join('\n')}

## Bumping a version

1. Change the pin in the root \`package.json\` **and** the matching entry in
   \`scripts/vendor-assets.js\` (version + filename), then \`npm install\`.
2. \`npm run vendor:assets\` — writes the new file and rewrites this README.
3. \`git rm\` the superseded file, and update the \`<script src>\` tags in
   \`public/index.html\` plus the \`SHELL_ASSETS\` list in \`public/sw.js\`.
   \`tests/pwa-shell-wiring.test.js\` and \`tests/tailwind-build.test.js\`
   fail if any of those fall out of sync, so the suite catches a half-done
   bump.
`;

fs.writeFileSync(path.join(OUT_DIR, 'README.md'), readme);
console.log('[vendor-assets] wrote public/vendor/README.md');
